export const syncGlobalDomains = [
  { type: 2, domains: ["ameritrade.com", "tdameritrade.com"] },
  { type: 3, domains: ["bankofamerica.com", "bofa.com", "mbna.com", "usecfo.com"] },
  { type: 4, domains: ["sprint.com", "sprintpcs.com", "nextel.com"] },
  { type: 0, domains: ["youtube.com", "google.com", "gmail.com"] },
  { type: 1, domains: ["apple.com", "icloud.com"] },
  { type: 5, domains: ["wellsfargo.com", "wf.com", "wellsfargoadvisors.com"] },
  { type: 6, domains: ["mymerrill.com", "ml.com", "merrilledge.com"] },
  { type: 7, domains: ["accountonline.com", "citi.com", "citibank.com", "citicards.com", "citibankonline.com"] },
  { type: 8, domains: ["cnet.com", "cnettv.com", "com.com", "download.com", "news.com", "search.com", "upload.com"] },
  { type: 9, domains: ["bananarepublic.com", "gap.com", "oldnavy.com", "piperlime.com"] },
  {
    type: 10,
    domains: [
      "bing.com",
      "hotmail.com",
      "live.com",
      "microsoft.com",
      "msn.com",
      "passport.net",
      "windows.com",
      "microsoftonline.com",
      "office.com",
      "office365.com",
      "microsoftstore.com",
      "xbox.com",
      "azure.com",
      "windowsazure.com",
      "cloud.microsoft",
    ],
  },
  { type: 11, domains: ["ua2go.com", "ual.com", "united.com", "unitedwifi.com"] },
  { type: 12, domains: ["overture.com", "yahoo.com"] },
  { type: 13, domains: ["zonealarm.com", "zonelabs.com"] },
  { type: 14, domains: ["paypal.com", "paypal-search.com"] },
  { type: 15, domains: ["avon.com", "youravon.com"] },
  {
    type: 16,
    domains: [
      "diapers.com",
      "soap.com",
      "wag.com",
      "yoyo.com",
      "beautybar.com",
      "casa.com",
      "afterschool.com",
      "vine.com",
      "bookworm.com",
      "look.com",
      "vinemarket.com",
    ],
  },
  { type: 17, domains: ["1800contacts.com", "800contacts.com"] },
  {
    type: 18,
    domains: [
      "amazon.com",
      "amazon.com.be",
      "amazon.ae",
      "amazon.ca",
      "amazon.co.uk",
      "amazon.com.au",
      "amazon.com.br",
      "amazon.com.mx",
      "amazon.com.tr",
      "amazon.de",
      "amazon.es",
      "amazon.fr",
      "amazon.in",
      "amazon.it",
      "amazon.nl",
      "amazon.pl",
      "amazon.sa",
      "amazon.se",
      "amazon.sg",
    ],
  },
  { type: 19, domains: ["cox.com", "cox.net", "coxbusiness.com"] },
  { type: 20, domains: ["mynortonaccount.com", "norton.com"] },
  { type: 21, domains: ["verizon.com", "verizon.net"] },
  { type: 22, domains: ["rakuten.com", "buy.com"] },
  { type: 23, domains: ["siriusxm.com", "sirius.com"] },
  { type: 24, domains: ["ea.com", "origin.com", "play4free.com", "tiberiumalliance.com"] },
  { type: 25, domains: ["37signals.com", "basecamp.com", "basecamphq.com", "highrisehq.com"] },
  { type: 26, domains: ["steampowered.com", "steamcommunity.com", "steamgames.com"] },
  { type: 27, domains: ["chart.io", "chartio.com"] },
  { type: 28, domains: ["gotomeeting.com", "citrixonline.com"] },
  { type: 29, domains: ["gogoair.com", "gogoinflight.com"] },
  { type: 30, domains: ["mysql.com", "oracle.com"] },
  { type: 31, domains: ["discover.com", "discovercard.com"] },
  { type: 32, domains: ["dcu.org", "dcu-online.org"] },
  { type: 33, domains: ["healthcare.gov", "cuidadodesalud.gov", "cms.gov"] },
  { type: 34, domains: ["pepco.com", "pepcoholdings.com"] },
  { type: 35, domains: ["century21.com", "21online.com"] },
  { type: 36, domains: ["comcast.com", "comcast.net", "xfinity.com"] },
  { type: 37, domains: ["cricketwireless.com", "aiowireless.com"] },
  { type: 38, domains: ["mandtbank.com", "mtb.com"] },
  { type: 39, domains: ["dropbox.com", "getdropbox.com"] },
  { type: 40, domains: ["snapfish.com", "snapfish.ca"] },
  { type: 41, domains: ["alibaba.com", "aliexpress.com", "aliyun.com", "net.cn"] },
  { type: 42, domains: ["playstation.com", "sonyentertainmentnetwork.com"] },
  {
    type: 43,
    domains: [
      "mercadolivre.com",
      "mercadolivre.com.br",
      "mercadolibre.com",
      "mercadolibre.com.ar",
      "mercadolibre.com.mx",
    ],
  },
  { type: 44, domains: ["zendesk.com", "zopim.com"] },
  { type: 45, domains: ["autodesk.com", "tinkercad.com"] },
  {
    type: 46,
    domains: [
      "railnation.ru",
      "railnation.de",
      "rail-nation.com",
      "railnation.gr",
      "railnation.us",
      "trucknation.de",
      "traviangames.com",
    ],
  },
  { type: 47, domains: ["wpcu.coop", "wpcuonline.com"] },
  { type: 48, domains: ["mathletics.com", "mathletics.com.au", "mathletics.co.uk"] },
  { type: 49, domains: ["discountbank.co.il", "telebank.co.il"] },
  { type: 50, domains: ["mi.com", "xiaomi.com"] },
  { type: 52, domains: ["postepay.it", "poste.it"] },
  { type: 51, domains: ["facebook.com", "messenger.com"] },
  { type: 53, domains: ["skysports.com", "skybet.com", "skyvegas.com"] },
  { type: 54, domains: ["disneymoviesanywhere.com", "go.com", "disney.com", "dadt.com", "disneyplus.com"] },
  { type: 55, domains: ["pokemon-gl.com", "pokemon.com"] },
  { type: 56, domains: ["myuv.com", "uvvu.com"] },
  { type: 58, domains: ["mdsol.com", "imedidata.com"] },
  { type: 57, domains: ["bank-yahav.co.il", "bankhapoalim.co.il"] },
  { type: 59, domains: ["sears.com", "shld.net"] },
  { type: 60, domains: ["xiami.com", "alipay.com"] },
  { type: 61, domains: ["belkin.com", "seedonk.com"] },
  { type: 62, domains: ["turbotax.com", "intuit.com"] },
  { type: 63, domains: ["shopify.com", "myshopify.com"] },
  {
    type: 64,
    domains: [
      "ebay.com",
      "ebay.at",
      "ebay.be",
      "ebay.ca",
      "ebay.ch",
      "ebay.cn",
      "ebay.co.jp",
      "ebay.co.th",
      "ebay.co.uk",
      "ebay.com.au",
      "ebay.com.hk",
      "ebay.com.my",
      "ebay.com.sg",
      "ebay.com.tw",
      "ebay.de",
      "ebay.es",
      "ebay.fr",
      "ebay.ie",
      "ebay.in",
      "ebay.it",
      "ebay.nl",
      "ebay.ph",
      "ebay.pl",
    ],
  },
  { type: 65, domains: ["techdata.com", "techdata.ch"] },
  { type: 66, domains: ["schwab.com", "schwabplan.com"] },
  { type: 68, domains: ["tesla.com", "teslamotors.com"] },
  { type: 69, domains: ["morganstanley.com", "morganstanleyclientserv.com", "stockplanconnect.com", "ms.com"] },
  { type: 70, domains: ["taxact.com", "taxactonline.com"] },
  {
    type: 71,
    domains: [
      "mediawiki.org",
      "wikibooks.org",
      "wikidata.org",
      "wikimedia.org",
      "wikinews.org",
      "wikipedia.org",
      "wikiquote.org",
      "wikisource.org",
      "wikiversity.org",
      "wikivoyage.org",
      "wiktionary.org",
    ],
  },
  {
    type: 72,
    domains: [
      "airbnb.at",
      "airbnb.be",
      "airbnb.ca",
      "airbnb.ch",
      "airbnb.cl",
      "airbnb.co.cr",
      "airbnb.co.id",
      "airbnb.co.in",
      "airbnb.co.kr",
      "airbnb.co.nz",
      "airbnb.co.uk",
      "airbnb.co.ve",
      "airbnb.com",
      "airbnb.com.ar",
      "airbnb.com.au",
      "airbnb.com.bo",
      "airbnb.com.br",
      "airbnb.com.bz",
      "airbnb.com.co",
      "airbnb.com.ec",
      "airbnb.com.gt",
      "airbnb.com.hk",
      "airbnb.com.hn",
      "airbnb.com.mt",
      "airbnb.com.my",
      "airbnb.com.ni",
      "airbnb.com.pa",
      "airbnb.com.pe",
      "airbnb.com.py",
      "airbnb.com.sg",
      "airbnb.com.sv",
      "airbnb.com.tr",
      "airbnb.com.tw",
      "airbnb.cz",
      "airbnb.de",
      "airbnb.dk",
      "airbnb.es",
      "airbnb.fi",
      "airbnb.fr",
      "airbnb.gr",
      "airbnb.gy",
      "airbnb.hu",
      "airbnb.ie",
      "airbnb.is",
      "airbnb.it",
      "airbnb.jp",
      "airbnb.mx",
      "airbnb.nl",
      "airbnb.no",
      "airbnb.pl",
      "airbnb.pt",
      "airbnb.ru",
      "airbnb.se",
    ],
  },
  {
    type: 73,
    domains: [
      "eventbrite.at",
      "eventbrite.be",
      "eventbrite.ca",
      "eventbrite.ch",
      "eventbrite.cl",
      "eventbrite.co",
      "eventbrite.co.nz",
      "eventbrite.co.uk",
      "eventbrite.com",
      "eventbrite.com.ar",
      "eventbrite.com.au",
      "eventbrite.com.br",
      "eventbrite.com.mx",
      "eventbrite.com.pe",
      "eventbrite.de",
      "eventbrite.dk",
      "eventbrite.es",
      "eventbrite.fi",
      "eventbrite.fr",
      "eventbrite.hk",
      "eventbrite.ie",
      "eventbrite.it",
      "eventbrite.nl",
      "eventbrite.pt",
      "eventbrite.se",
      "eventbrite.sg",
    ],
  },
  {
    type: 74,
    domains: [
      "stackexchange.com",
      "superuser.com",
      "stackoverflow.com",
      "serverfault.com",
      "mathoverflow.net",
      "askubuntu.com",
      "stackapps.com",
    ],
  },
  { type: 75, domains: ["docusign.com", "docusign.net"] },
  {
    type: 76,
    domains: [
      "envato.com",
      "themeforest.net",
      "codecanyon.net",
      "videohive.net",
      "audiojungle.net",
      "graphicriver.net",
      "photodune.net",
      "3docean.net",
    ],
  },
  { type: 77, domains: ["x10hosting.com", "x10premium.com"] },
  { type: 78, domains: ["dnsomatic.com", "opendns.com", "umbrella.com"] },
  {
    type: 79,
    domains: [
      "cagreatamerica.com",
      "canadaswonderland.com",
      "carowinds.com",
      "cedarfair.com",
      "cedarpoint.com",
      "dorneypark.com",
      "kingsdominion.com",
      "knotts.com",
      "miadventure.com",
      "schlitterbahn.com",
      "valleyfair.com",
      "visitkingsisland.com",
      "worldsoffun.com",
    ],
  },
  { type: 80, domains: ["ubnt.com", "ui.com"] },
  { type: 81, domains: ["discordapp.com", "discord.com"] },
  { type: 82, domains: ["netcup.de", "netcup.eu", "customercontrolpanel.de"] },
  {
    type: 83,
    domains: [
      "yandex.com",
      "ya.ru",
      "yandex.az",
      "yandex.by",
      "yandex.co.il",
      "yandex.com.am",
      "yandex.com.ge",
      "yandex.com.tr",
      "yandex.ee",
      "yandex.fi",
      "yandex.fr",
      "yandex.kg",
      "yandex.kz",
      "yandex.lt",
      "yandex.lv",
      "yandex.md",
      "yandex.pl",
      "yandex.ru",
      "yandex.tj",
      "yandex.tm",
      "yandex.ua",
      "yandex.uz",
    ],
  },
  { type: 84, domains: ["sonyentertainmentnetwork.com", "sony.com"] },
  { type: 85, domains: ["proton.me", "protonmail.com", "protonvpn.com"] },
  { type: 86, domains: ["ubisoft.com", "ubi.com"] },
  { type: 87, domains: ["transferwise.com", "wise.com"] },
  {
    type: 88,
    domains: [
      "takeaway.com",
      "just-eat.dk",
      "just-eat.no",
      "just-eat.fr",
      "just-eat.ch",
      "lieferando.de",
      "lieferando.at",
      "thuisbezorgd.nl",
      "pyszne.pl",
    ],
  },
  { type: 89, domains: ["atlassian.com", "bitbucket.org", "trello.com", "statuspage.io", "atlassian.net", "jira.com"] },
  {
    type: 90,
    domains: [
      "pinterest.com",
      "pinterest.com.au",
      "pinterest.cl",
      "pinterest.de",
      "pinterest.dk",
      "pinterest.es",
      "pinterest.fr",
      "pinterest.co.uk",
      "pinterest.jp",
      "pinterest.co.kr",
      "pinterest.nz",
      "pinterest.pt",
      "pinterest.se",
    ],
  },
  { type: 91, domains: ["twitter.com", "x.com"] },
] as const
