import * as v from "valibot"

const adminSettingsBooleanKeySchema = v.picklist([
  "webVaultEnabled",
  "sendsAllowed",
  "signupsAllowed",
  "signupsVerify",
  "invitationsAllowed",
  "emergencyAccessAllowed",
  "emailChangeAllowed",
  "passwordHintsAllowed",
  "showPasswordHint",
  "twoFactorEnabled",
  "adminTokenDisabled",
  "disableIconDownload",
  "disable2faRemember",
  "requireDeviceEmail",
  "reloadTemplates",
  "increaseNoteSizeLimit",
  "ssoEnabled",
  "ssoOnly",
  "ssoSignupsMatchEmail",
  "ssoAllowUnknownEmailVerification",
  "ssoPkce",
  "ssoDebugTokens",
  "mailEnabled",
  "useSendmail",
  "smtpEmbedImages",
  "smtpAcceptInvalidCerts",
  "smtpAcceptInvalidHostnames",
  "email2faEnforceOnInvite",
  "email2faAutoFallback",
  "yubicoEnabled",
  "duoEnabled",
])

const adminSettingsTextKeySchema = v.picklist([
  "domain",
  "invitationOrgName",
  "signupsDomainsWhitelist",
  "orgCreationUsers",
  "adminToken",
  "ipHeader",
  "ipHeaderTrustedProxies",
  "iconService",
  "httpRequestBlockRegex",
  "allowedIframeAncestors",
  "allowedConnectSrc",
  "logTimestampFormat",
  "logLevel",
  "ssoClientId",
  "ssoClientSecret",
  "ssoAuthority",
  "ssoScopes",
  "ssoAuthorizeExtraParams",
  "ssoAudienceTrusted",
  "smtpHost",
  "smtpFrom",
  "smtpFromName",
  "smtpUsername",
  "smtpPassword",
  "smtpAuthMechanism",
  "heloName",
  "yubicoClientId",
  "yubicoSecretKey",
  "yubicoServer",
  "duoIkey",
  "duoSkey",
  "duoHost",
])

const adminSettingsNumberKeySchema = v.picklist([
  "userAttachmentLimit",
  "orgAttachmentLimit",
  "userSendLimit",
  "trashAutoDeleteDays",
  "incomplete2faTimeLimit",
  "signupsVerifyResendTime",
  "signupsVerifyResendLimit",
  "invitationExpirationHours",
  "passwordIterations",
  "iconRedirectCode",
  "iconCacheTtl",
  "iconCacheNegttl",
  "iconDownloadTimeout",
  "loginRatelimitSeconds",
  "loginRatelimitMaxBurst",
  "adminSessionLifetime",
  "smtpTimeout",
  "emailTokenSize",
  "emailExpirationTime",
  "emailAttemptsLimit",
])

const adminSettingsOverrideSchema = v.picklist([
  ...adminSettingsBooleanKeySchema.options,
  ...adminSettingsTextKeySchema.options,
  ...adminSettingsNumberKeySchema.options,
])

const adminSettingsPasswordKeySchema = v.picklist([
  "hibpApiKey",
  "adminToken",
  "ssoClientSecret",
  "smtpPassword",
  "yubicoSecretKey",
  "duoSkey",
  "databaseUrl",
])

const adminReadOnlySettingsSchema = v.object({
  dataFolder: v.string(),
  databaseUrl: v.string(),
  webVaultFolder: v.string(),
  domainOrigin: v.string(),
  domainPath: v.string(),
  iconServiceUrl: v.string(),
  ssoCallbackPath: v.string(),
  smtpSecurity: v.string(),
  smtpPort: v.pipe(v.number(), v.integer(), v.minValue(1)),
  smtpImageSource: v.string(),
  enableWebsocket: v.boolean(),
  email2faEnabled: v.boolean(),
  adminPageSecurityBypass: v.boolean(),
  sessionLifetimeMinutes: v.pipe(v.number(), v.integer(), v.minValue(1)),
  jobPollIntervalMs: v.pipe(v.number(), v.integer(), v.minValue(0)),
  sendPurgeSchedule: v.string(),
})

const nonNegativeIntegerSchema = v.pipe(v.number(), v.integer(), v.minValue(0))

export const adminSettingsSchema = v.object({
  domain: v.string(),
  webVaultEnabled: v.boolean(),
  sendsAllowed: v.boolean(),
  signupsAllowed: v.boolean(),
  signupsVerify: v.boolean(),
  signupsVerifyResendTime: nonNegativeIntegerSchema,
  signupsVerifyResendLimit: nonNegativeIntegerSchema,
  signupsDomainsWhitelist: v.string(),
  orgCreationUsers: v.string(),
  invitationsAllowed: v.boolean(),
  invitationExpirationHours: v.pipe(v.number(), v.integer(), v.minValue(1)),
  emergencyAccessAllowed: v.boolean(),
  emailChangeAllowed: v.boolean(),
  passwordIterations: v.pipe(v.number(), v.integer(), v.minValue(100_000)),
  passwordHintsAllowed: v.boolean(),
  showPasswordHint: v.boolean(),
  invitationOrgName: v.string(),
  hibpApiKey: v.string(),
  adminToken: v.string(),
  twoFactorEnabled: v.boolean(),
  adminTokenDisabled: v.boolean(),
  disableIconDownload: v.boolean(),
  userAttachmentLimit: nonNegativeIntegerSchema,
  orgAttachmentLimit: nonNegativeIntegerSchema,
  userSendLimit: nonNegativeIntegerSchema,
  trashAutoDeleteDays: nonNegativeIntegerSchema,
  incomplete2faTimeLimit: nonNegativeIntegerSchema,
  ipHeader: v.string(),
  ipHeaderTrustedProxies: v.string(),
  iconService: v.string(),
  httpRequestBlockRegex: v.string(),
  iconRedirectCode: nonNegativeIntegerSchema,
  iconCacheTtl: nonNegativeIntegerSchema,
  iconCacheNegttl: nonNegativeIntegerSchema,
  iconDownloadTimeout: nonNegativeIntegerSchema,
  disable2faRemember: v.boolean(),
  requireDeviceEmail: v.boolean(),
  reloadTemplates: v.boolean(),
  increaseNoteSizeLimit: v.boolean(),
  logTimestampFormat: v.string(),
  logLevel: v.string(),
  allowedIframeAncestors: v.string(),
  allowedConnectSrc: v.string(),
  loginRatelimitSeconds: nonNegativeIntegerSchema,
  loginRatelimitMaxBurst: nonNegativeIntegerSchema,
  adminSessionLifetime: nonNegativeIntegerSchema,
  ssoEnabled: v.boolean(),
  ssoOnly: v.boolean(),
  ssoSignupsMatchEmail: v.boolean(),
  ssoAllowUnknownEmailVerification: v.boolean(),
  ssoClientId: v.string(),
  ssoClientSecret: v.string(),
  ssoAuthority: v.string(),
  ssoScopes: v.string(),
  ssoAuthorizeExtraParams: v.string(),
  ssoAudienceTrusted: v.string(),
  ssoPkce: v.boolean(),
  ssoDebugTokens: v.boolean(),
  mailEnabled: v.boolean(),
  useSendmail: v.boolean(),
  smtpHost: v.string(),
  smtpFrom: v.string(),
  smtpFromName: v.string(),
  smtpUsername: v.string(),
  smtpPassword: v.string(),
  smtpAuthMechanism: v.string(),
  smtpTimeout: nonNegativeIntegerSchema,
  heloName: v.string(),
  smtpEmbedImages: v.boolean(),
  smtpAcceptInvalidCerts: v.boolean(),
  smtpAcceptInvalidHostnames: v.boolean(),
  emailTokenSize: nonNegativeIntegerSchema,
  emailExpirationTime: nonNegativeIntegerSchema,
  emailAttemptsLimit: nonNegativeIntegerSchema,
  email2faEnforceOnInvite: v.boolean(),
  email2faAutoFallback: v.boolean(),
  yubicoEnabled: v.boolean(),
  yubicoClientId: v.string(),
  yubicoSecretKey: v.string(),
  yubicoServer: v.string(),
  duoEnabled: v.boolean(),
  duoIkey: v.string(),
  duoSkey: v.string(),
  duoHost: v.string(),
  readOnly: adminReadOnlySettingsSchema,
  overrides: v.array(adminSettingsOverrideSchema),
  environmentOverrides: v.array(adminSettingsOverrideSchema),
})

export type AdminSettings = v.InferOutput<typeof adminSettingsSchema>
export type AdminSettingsBooleanKey = v.InferOutput<typeof adminSettingsBooleanKeySchema>
export type AdminSettingsNumberKey = v.InferOutput<typeof adminSettingsNumberKeySchema>
export type AdminSettingsOverride = v.InferOutput<typeof adminSettingsOverrideSchema>
export type AdminSettingsPasswordKey = v.InferOutput<typeof adminSettingsPasswordKeySchema>
export type AdminSettingsTextKey = v.InferOutput<typeof adminSettingsTextKeySchema>
export type AdminReadOnlySettings = v.InferOutput<typeof adminReadOnlySettingsSchema>
