import { type JSX, Match, Show, Switch } from "solid-js"
import { Dynamic } from "solid-js/web"
import { Checkbox } from "#ui/input/check/Checkbox.jsx"
import { Input } from "#ui/input/input/Input.jsx"
import { Label } from "#ui/input/label/Label.jsx"
import { SelectSingleNative } from "#ui/input/select/SelectSingleNative.jsx"
import { Button } from "#ui/interactive/button/Button.jsx"
import { CardWrapper } from "#ui/static/card/CardWrapper.jsx"
import { Icon } from "#ui/static/icon/Icon.jsx"
import { classMerge } from "#ui/utils/classMerge.js"
import { vaultSvgIcons } from "../../demo/vaultSvgIcons.js"
import { twoFactorProviderType } from "../model/twoFactorProviderType.js"
import {
  type AuthTwoFactorChallengeCardProps,
  authTwoFactorChallengeCardStateCreate,
} from "./authTwoFactorChallengeCardStateCreate.js"

const providerLabels: Record<number, string> = {
  [twoFactorProviderType.authenticator]: "Authenticator App",
  [twoFactorProviderType.email]: "Email Verification",
  [twoFactorProviderType.duo]: "Duo Security",
  [twoFactorProviderType.yubikey]: "YubiKey OTP",
  [twoFactorProviderType.webauthn]: "FIDO2 / WebAuthn Security Key",
  [twoFactorProviderType.recoveryCode]: "Recovery Code",
}

export function AuthTwoFactorChallengeCard(props: AuthTwoFactorChallengeCardProps): JSX.Element {
  const state = authTwoFactorChallengeCardStateCreate(props)

  return (
    <CardWrapper
      class={classMerge(
        "w-full max-w-md space-y-6 rounded-2xl border border-slate-200 bg-white p-8 shadow-xl dark:border-slate-800 dark:bg-slate-900",
        props.class,
      )}
    >
      <div class="text-center">
        <div class="mx-auto flex size-14 items-center justify-center rounded-2xl bg-blue-50 text-blue-600 ring-8 ring-blue-50/50 dark:bg-blue-950/50 dark:text-blue-400 dark:ring-blue-950/30">
          <Icon path={vaultSvgIcons.twoFactor} class="size-7 text-blue-600 dark:text-blue-400" />
        </div>
        <Dynamic
          component={state.headingLevel()}
          class="mt-4 font-bold text-2xl text-slate-900 tracking-tight dark:text-slate-50"
        >
          Two-Step Verification
        </Dynamic>
        <p class="mt-1 text-xs text-slate-600 dark:text-slate-400">
          Complete second-factor authentication to unlock your encrypted vault.
        </p>
      </div>

      <Show when={state.errorMessage()}>
        {(msg) => (
          <div
            role="alert"
            class="rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700 dark:border-red-900/50 dark:bg-red-950/40 dark:text-red-300"
          >
            {msg()}
          </div>
        )}
      </Show>

      <Show when={state.emailSentMessage()}>
        {(msg) => (
          <div
            role="status"
            class="rounded-lg border border-blue-200 bg-blue-50 p-3 text-xs text-blue-700 dark:border-blue-900/50 dark:bg-blue-950/40 dark:text-blue-300"
          >
            {msg()}
          </div>
        )}
      </Show>

      <Show when={state.availableProviders().length > 1}>
        <div>
          <Label for="two-factor-method-select" class="block text-xs font-medium text-slate-700 dark:text-slate-300">
            Verification Method
          </Label>
          <div class="mt-1">
            <SelectSingleNative
              id="two-factor-method-select"
              valueSignal={state.selectedProviderSignal}
              getOptions={state.availableProviderKeys}
              valueText={(val) => providerLabels[Number(val)] ?? val}
              class="h-9 w-full rounded-md border-slate-200 bg-slate-50 px-3 text-xs text-slate-800 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-200"
            />
          </div>
        </div>
      </Show>

      <form onSubmit={state.handleSubmit} class="space-y-4">
        <Switch>
          <Match when={state.selectedProvider() === twoFactorProviderType.authenticator}>
            <div>
              <Label for="2fa-token-authenticator" class="block text-xs font-medium text-slate-700 dark:text-slate-300">
                6-Digit Security Code
              </Label>
              <Input
                id="2fa-token-authenticator"
                type="text"
                inputmode="numeric"
                autocomplete="one-time-code"
                placeholder="123456"
                maxlength={8}
                value={state.token()}
                onInput={(e) => state.setToken(e.currentTarget.value)}
                required
                autofocus
                class="mt-1 h-10 w-full text-center font-mono text-base tracking-widest rounded-md border-slate-200 bg-slate-50 px-3 focus:bg-white dark:border-slate-700 dark:bg-slate-800"
              />
              <p class="mt-1 text-[11px] text-slate-500 dark:text-slate-400">
                Enter the verification code generated by your authenticator app.
              </p>
            </div>
          </Match>

          <Match when={state.selectedProvider() === twoFactorProviderType.email}>
            <div class="space-y-3">
              <div class="rounded-md border border-slate-200 bg-slate-50 p-3 text-xs text-slate-700 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-300">
                <div class="flex items-center gap-2">
                  <Icon path={vaultSvgIcons.email} class="size-4 text-blue-600 dark:text-blue-400" />
                  <span class="font-medium">
                    {state.obscuredEmail() ? `Sent to ${state.obscuredEmail()}` : "Email 2FA Verification"}
                  </span>
                </div>
                <div class="mt-2">
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    class="text-xs"
                    disabled={state.isEmailSending()}
                    onClick={state.handleSendLoginEmail}
                  >
                    <Show when={state.isEmailSending()} fallback="Send Verification Email">
                      Sending Code...
                    </Show>
                  </Button>
                </div>
              </div>

              <div>
                <Label for="2fa-token-email" class="block text-xs font-medium text-slate-700 dark:text-slate-300">
                  Email Verification Code
                </Label>
                <Input
                  id="2fa-token-email"
                  type="text"
                  inputmode="numeric"
                  autocomplete="one-time-code"
                  placeholder="123456"
                  value={state.token()}
                  onInput={(e) => state.setToken(e.currentTarget.value)}
                  required
                  class="mt-1 h-10 w-full text-center font-mono text-base tracking-widest rounded-md border-slate-200 bg-slate-50 px-3 focus:bg-white dark:border-slate-700 dark:bg-slate-800"
                />
              </div>
            </div>
          </Match>

          <Match when={state.selectedProvider() === twoFactorProviderType.webauthn}>
            <div class="space-y-3">
              <div class="rounded-md border border-slate-200 bg-slate-50 p-3 text-xs text-slate-700 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-300">
                <div class="flex items-center gap-2">
                  <Icon path={vaultSvgIcons.key} class="size-4 text-blue-600 dark:text-blue-400" />
                  <span class="font-medium">FIDO2 / WebAuthn Security Key</span>
                </div>
                <p class="mt-1 text-[11px] text-slate-500 dark:text-slate-400">
                  Click the button below to prompt your hardware key or passkey.
                </p>
                <div class="mt-2">
                  <Button
                    type="button"
                    variant="filledBlue"
                    size="sm"
                    class="text-xs font-medium"
                    onClick={state.handleWebAuthnPrompt}
                  >
                    Use Hardware Security Key
                  </Button>
                </div>
                <Show when={state.webAuthnStatus()}>
                  {(status) => <p class="mt-2 text-xs font-medium text-blue-600 dark:text-blue-400">{status()}</p>}
                </Show>
              </div>

              <div>
                <Label for="2fa-token-webauthn" class="block text-xs font-medium text-slate-700 dark:text-slate-300">
                  WebAuthn Assertion JSON (Auto-filled by Security Key)
                </Label>
                <Input
                  id="2fa-token-webauthn"
                  type="text"
                  placeholder="WebAuthn response JSON"
                  value={state.token()}
                  onInput={(e) => state.setToken(e.currentTarget.value)}
                  required
                  class="mt-1 h-9 w-full font-mono text-xs rounded-md border-slate-200 bg-slate-50 px-3 focus:bg-white dark:border-slate-700 dark:bg-slate-800"
                />
              </div>
            </div>
          </Match>

          <Match when={state.selectedProvider() === twoFactorProviderType.yubikey}>
            <div>
              <Label for="2fa-token-yubikey" class="block text-xs font-medium text-slate-700 dark:text-slate-300">
                YubiKey One-Time Password
              </Label>
              <Input
                id="2fa-token-yubikey"
                type="password"
                autocomplete="off"
                placeholder="Touch your YubiKey"
                value={state.token()}
                onInput={(e) => state.setToken(e.currentTarget.value)}
                required
                autofocus
                class="mt-1 h-10 w-full font-mono text-sm rounded-md border-slate-200 bg-slate-50 px-3 focus:bg-white dark:border-slate-700 dark:bg-slate-800"
              />
              <p class="mt-1 text-[11px] text-slate-500 dark:text-slate-400">
                Insert your YubiKey into a USB port and touch the metal contact button.
              </p>
            </div>
          </Match>

          <Match when={state.selectedProvider() === twoFactorProviderType.duo}>
            <div>
              <Label for="2fa-token-duo" class="block text-xs font-medium text-slate-700 dark:text-slate-300">
                Duo Passcode / Push Token
              </Label>
              <Input
                id="2fa-token-duo"
                type="text"
                placeholder="Enter Duo passcode"
                value={state.token()}
                onInput={(e) => state.setToken(e.currentTarget.value)}
                required
                autofocus
                class="mt-1 h-10 w-full font-mono text-sm rounded-md border-slate-200 bg-slate-50 px-3 focus:bg-white dark:border-slate-700 dark:bg-slate-800"
              />
              <p class="mt-1 text-[11px] text-slate-500 dark:text-slate-400">
                Enter the passcode generated in your Duo Mobile application.
              </p>
            </div>
          </Match>

          <Match when={state.selectedProvider() === twoFactorProviderType.recoveryCode}>
            <div>
              <Label for="2fa-token-recovery" class="block text-xs font-medium text-slate-700 dark:text-slate-300">
                Account Recovery Code
              </Label>
              <Input
                id="2fa-token-recovery"
                type="text"
                placeholder="Enter alphanumeric recovery code"
                value={state.token()}
                onInput={(e) => state.setToken(e.currentTarget.value)}
                required
                autofocus
                class="mt-1 h-10 w-full font-mono text-sm rounded-md border-slate-200 bg-slate-50 px-3 focus:bg-white dark:border-slate-700 dark:bg-slate-800"
              />
              <p class="mt-1 text-[11px] text-slate-500 dark:text-slate-400">
                Use one of your emergency recovery codes to access your account if you lost your two-step devices.
              </p>
            </div>
          </Match>
        </Switch>

        <div class="pt-1">
          <Checkbox id="remember-device" checked={state.rememberDevice()} onChange={state.setRememberDevice}>
            <span class="select-none text-xs text-slate-600 dark:text-slate-400">Remember this device for 30 days</span>
          </Checkbox>
        </div>

        <div class="flex flex-col gap-2 pt-2">
          <Button
            type="submit"
            variant="filledBlue"
            class="w-full justify-center text-xs font-semibold"
            disabled={state.isSubmitting()}
          >
            <Show when={state.isSubmitting()} fallback="Verify & Unlock Vault">
              Verifying & Decrypting...
            </Show>
          </Button>

          <Button
            type="button"
            variant="outline"
            class="w-full justify-center text-xs text-slate-600 dark:text-slate-400"
            disabled={state.isSubmitting()}
            onClick={state.cancel}
          >
            Back to Login
          </Button>
        </div>
      </form>
    </CardWrapper>
  )
}
