import type { AdminUser } from "../admin/adminUserSchema.js"

export const adminUsersDemoData: readonly AdminUser[] = [
  {
    id: "user-alex-rivera",
    name: "Alex Rivera",
    email: "alex.rivera@acme.internal",
    status: "active",
    role: "owner",
    twoFactorEnabled: true,
    organizationCount: 2,
    organizations: [
      { id: "organization-acme-core", name: "Acme Core Infrastructure", role: "owner" },
      { id: "organization-acme-design", name: "Acme Design Studio", role: "admin" },
    ],
    ssoIdentifier: "alex-rivera-entra-001",
    emailVerified: true,
    cipherCount: 148,
    attachmentCount: 12,
    attachmentSizeBytes: 25_600_000,
    lastActiveAt: "2026-08-29T08:42:00Z",
    createdAt: "2025-01-15T09:20:00Z",
    sessionsDeauthorizedAt: null,
    invitationSentAt: null,
    overridden: true,
  },
  {
    id: "user-morgan-lee",
    name: "Morgan Lee",
    email: "morgan.lee@acme.internal",
    status: "active",
    role: "admin",
    twoFactorEnabled: true,
    organizationCount: 1,
    organizations: [{ id: "organization-acme-core", name: "Acme Core Infrastructure", role: "manager" }],
    ssoIdentifier: "morgan-lee-okta-042",
    emailVerified: true,
    cipherCount: 63,
    attachmentCount: 3,
    attachmentSizeBytes: 4_800_000,
    lastActiveAt: "2026-08-28T16:05:00Z",
    createdAt: "2025-04-02T11:10:00Z",
    sessionsDeauthorizedAt: null,
    invitationSentAt: null,
    overridden: false,
  },
  {
    id: "user-jamie-patel",
    name: "Jamie Patel",
    email: "jamie.patel@acme.internal",
    status: "disabled",
    role: "user",
    twoFactorEnabled: false,
    organizationCount: 1,
    organizations: [{ id: "organization-legacy-labs", name: "Legacy Labs", role: "user" }],
    ssoIdentifier: null,
    emailVerified: true,
    cipherCount: 17,
    attachmentCount: 0,
    attachmentSizeBytes: 0,
    lastActiveAt: "2026-07-11T13:22:00Z",
    createdAt: "2025-08-18T14:30:00Z",
    sessionsDeauthorizedAt: null,
    invitationSentAt: null,
    overridden: false,
  },
  {
    id: "user-taylor-nguyen",
    name: "Taylor Nguyen",
    email: "taylor.nguyen@acme.internal",
    status: "invited",
    role: "user",
    twoFactorEnabled: false,
    organizationCount: 0,
    organizations: [],
    ssoIdentifier: null,
    emailVerified: false,
    cipherCount: 0,
    attachmentCount: 0,
    attachmentSizeBytes: 0,
    lastActiveAt: null,
    createdAt: "2026-08-27T10:15:00Z",
    sessionsDeauthorizedAt: null,
    invitationSentAt: "2026-08-27T10:15:00Z",
    overridden: false,
  },
]
