import type { AdminSettings } from "../admin/adminSettingsSchema.js"

export const adminSettingsDemoData: AdminSettings = {
  domain: "https://vault.demo.internal",
  webVaultEnabled: true,
  sendsAllowed: true,
  signupsAllowed: true,
  signupsVerify: false,
  signupsVerifyResendTime: 3600,
  signupsVerifyResendLimit: 6,
  signupsDomainsWhitelist: "",
  orgCreationUsers: "all",
  invitationsAllowed: true,
  invitationExpirationHours: 120,
  emergencyAccessAllowed: true,
  emailChangeAllowed: true,
  passwordIterations: 600_000,
  passwordHintsAllowed: true,
  showPasswordHint: false,
  invitationOrgName: "OneWarden Demo",
  hibpApiKey: "",
  adminToken: "demo-admin-token",
  twoFactorEnabled: true,
  adminTokenDisabled: false,
  disableIconDownload: false,
  userAttachmentLimit: 10_240,
  orgAttachmentLimit: 102_400,
  userSendLimit: 1_024,
  trashAutoDeleteDays: 30,
  incomplete2faTimeLimit: 3,
  ipHeader: "X-Real-IP",
  ipHeaderTrustedProxies: "local",
  iconService: "internal",
  httpRequestBlockRegex: "",
  iconRedirectCode: 302,
  iconCacheTtl: 2_592_000,
  iconCacheNegttl: 259_200,
  iconDownloadTimeout: 10,
  disable2faRemember: false,
  requireDeviceEmail: false,
  reloadTemplates: false,
  increaseNoteSizeLimit: false,
  logTimestampFormat: "%Y-%m-%d %H:%M:%S.%3f",
  logLevel: "info",
  allowedIframeAncestors: "",
  allowedConnectSrc: "",
  loginRatelimitSeconds: 60,
  loginRatelimitMaxBurst: 10,
  adminSessionLifetime: 20,
  ssoEnabled: false,
  ssoOnly: false,
  ssoSignupsMatchEmail: true,
  ssoAllowUnknownEmailVerification: false,
  ssoClientId: "demo-client",
  ssoClientSecret: "demo-client-secret",
  ssoAuthority: "https://identity.demo.internal",
  ssoScopes: "email profile",
  ssoAuthorizeExtraParams: "",
  ssoAudienceTrusted: "",
  ssoPkce: true,
  ssoDebugTokens: false,
  mailEnabled: true,
  useSendmail: false,
  smtpHost: "smtp.demo.internal",
  smtpFrom: "vault@demo.internal",
  smtpFromName: "OneWarden Demo",
  smtpUsername: "demo-smtp",
  smtpPassword: "demo-smtp-password",
  smtpAuthMechanism: "Plain",
  smtpTimeout: 15,
  heloName: "vault.demo.internal",
  smtpEmbedImages: true,
  smtpAcceptInvalidCerts: false,
  smtpAcceptInvalidHostnames: false,
  emailTokenSize: 6,
  emailExpirationTime: 600,
  emailAttemptsLimit: 3,
  email2faEnforceOnInvite: false,
  email2faAutoFallback: false,
  yubicoEnabled: false,
  yubicoClientId: "",
  yubicoSecretKey: "",
  yubicoServer: "https://api.yubico.com/wsapi/2.0",
  duoEnabled: false,
  duoIkey: "",
  duoSkey: "",
  duoHost: "api-xxxxxxxx.duosecurity.com",
  readOnly: {
    dataFolder: "data",
    databaseUrl: "sqlite://data/db.sqlite3",
    webVaultFolder: "web-vault/",
    domainOrigin: "https://vault.demo.internal",
    domainPath: "",
    iconServiceUrl: "",
    ssoCallbackPath: "https://vault.demo.internal/identity/connect/oidc-signin",
    smtpSecurity: "starttls",
    smtpPort: 587,
    smtpImageSource: "cid:",
    enableWebsocket: true,
    email2faEnabled: true,
    adminPageSecurityBypass: false,
    sessionLifetimeMinutes: 60,
    jobPollIntervalMs: 30_000,
    sendPurgeSchedule: "0 5 * * * *",
  },
  overrides: ["domain", "mailEnabled", "passwordIterations", "ssoAuthority"],
  environmentOverrides: ["smtpHost", "ipHeaderTrustedProxies", "adminSessionLifetime"],
}
