import type { AdminUser } from "../admin/adminUserSchema.js"

export const adminUsersDemoData: readonly AdminUser[] = [
  {
    id: "user-alex-rivera",
    name: "Alex Rivera",
    email: "alex.rivera@acme.internal",
    status: "active",
    role: "owner",
    twoFactorEnabled: true,
    organizationCount: 2,
    lastActiveAt: "2026-08-29T08:42:00Z",
    createdAt: "2025-01-15T09:20:00Z",
    overridden: true,
  },
  {
    id: "user-morgan-lee",
    name: "Morgan Lee",
    email: "morgan.lee@acme.internal",
    status: "active",
    role: "admin",
    twoFactorEnabled: true,
    organizationCount: 1,
    lastActiveAt: "2026-08-28T16:05:00Z",
    createdAt: "2025-04-02T11:10:00Z",
    overridden: false,
  },
  {
    id: "user-jamie-patel",
    name: "Jamie Patel",
    email: "jamie.patel@acme.internal",
    status: "disabled",
    role: "user",
    twoFactorEnabled: false,
    organizationCount: 1,
    lastActiveAt: "2026-07-11T13:22:00Z",
    createdAt: "2025-08-18T14:30:00Z",
    overridden: false,
  },
  {
    id: "user-taylor-nguyen",
    name: "Taylor Nguyen",
    email: "taylor.nguyen@acme.internal",
    status: "invited",
    role: "user",
    twoFactorEnabled: false,
    organizationCount: 0,
    lastActiveAt: null,
    createdAt: "2026-08-27T10:15:00Z",
    overridden: false,
  },
]
