import type { AdminOrganization } from "../admin/adminOrganizationSchema.js"

export const adminOrganizationsDemoData: readonly AdminOrganization[] = [
  {
    id: "organization-acme-core",
    uuid: "9a7f4f2e-02ae-4e57-9d8f-1a73c14d4c01",
    name: "Acme Core Infrastructure",
    billingEmail: "billing@acme.internal",
    status: "active",
    plan: "enterprise",
    ownerName: "Alex Rivera",
    memberCount: 24,
    cipherCount: 148,
    attachmentCount: 12,
    attachmentSizeBytes: 25_600_000,
    collectionCount: 9,
    groupCount: 4,
    eventCount: 312,
    twoFactorRequired: true,
    ssoEnabled: false,
    createdAt: "2024-11-10T11:00:00Z",
  },
  {
    id: "organization-acme-design",
    uuid: "f3a1c6d4-7b92-4c08-a5e1-63d9b2f84720",
    name: "Acme Design Studio",
    billingEmail: "design-ops@acme.internal",
    status: "active",
    plan: "premium",
    ownerName: "Morgan Lee",
    memberCount: 8,
    cipherCount: 63,
    attachmentCount: 3,
    attachmentSizeBytes: 4_800_000,
    collectionCount: 4,
    groupCount: 2,
    eventCount: 87,
    twoFactorRequired: false,
    ssoEnabled: true,
    createdAt: "2025-03-01T10:15:00Z",
  },
  {
    id: "organization-legacy-labs",
    uuid: "1c4e8a90-5d33-46b7-9f21-0ab6d8e3c745",
    name: "Legacy Labs",
    billingEmail: "owner@legacy-labs.internal",
    status: "disabled",
    plan: "free",
    ownerName: "Jamie Patel",
    memberCount: 3,
    cipherCount: 17,
    attachmentCount: 0,
    attachmentSizeBytes: 0,
    collectionCount: 1,
    groupCount: 0,
    eventCount: 14,
    twoFactorRequired: false,
    ssoEnabled: false,
    createdAt: "2023-06-21T08:30:00Z",
  },
]
