import type { VaultItem } from "./vaultItemSchema.js"

export const vaultDemoData: readonly VaultItem[] = [
  {
    id: "item-github-enterprise",
    title: "GitHub Enterprise",
    category: "login",
    ownership: "organization",
    organizationId: "organization-acme",
    collectionIds: ["collection-engineering"],
    folderId: "folder-engineering",
    vault: "Work",
    favorite: false,
    deletedAt: null,
    folder: "Engineering",
    username: "alex.rivera@acme.internal",
    password: "wz9!kP#7mX2$vL9@qR5*tY8",
    passwordHistory: [{ password: "vL7!nR#4kW9$pT2@xM6", lastUsedDate: "2026-06-03T15:24:00Z" }],
    url: "https://github.company.internal/login",
    totp: "492 018",
    passwordStrength: "Very Strong",
    notes: "Requires hardware U2F security key for secondary admin escalation.",
    customFields: [
      { label: "Organization", value: "acme-corp-core" },
      { label: "Recovery Token", value: "REC-9921-AF72-8810", concealed: true },
      { label: "SSH Key Fingerprint", value: "SHA256:m982jKL8912nbv00912m" },
    ],
    createdAt: "2025-01-15 09:20",
    updatedAt: "2026-08-20 14:32",
  },
  {
    id: "item-aws-console",
    title: "AWS Console - Root Admin",
    category: "login",
    ownership: "organization",
    organizationId: "organization-acme",
    collectionIds: ["collection-infrastructure"],
    folderId: "folder-infrastructure",
    vault: "Work",
    favorite: false,
    deletedAt: null,
    folder: "Infrastructure",
    username: "root-admin@acme-cloud.internal",
    password: "k9#Vp!28mQ$zL8*wX5@tR1",
    url: "https://aws.amazon.com/console",
    totp: "847 129",
    passwordStrength: "Very Strong",
    notes: "Emergency root credentials for primary AWS organization partition.",
    customFields: [
      { label: "Account ID", value: "1092-8834-0019" },
      { label: "MFA Serial ARN", value: "arn:aws:iam::109288340019:mfa/root" },
      { label: "Support Tier", value: "Enterprise 24/7" },
    ],
    createdAt: "2024-11-10 11:00",
    updatedAt: "2026-07-18 16:45",
  },
  {
    id: "item-stripe-dashboard",
    title: "Stripe Payment Dashboard",
    category: "login",
    ownership: "organization",
    organizationId: "organization-acme",
    collectionIds: ["collection-finance"],
    folderId: "folder-finance",
    vault: "Work",
    favorite: false,
    deletedAt: null,
    folder: "Finance",
    username: "alex.rivera@startup.fyi",
    password: "sP7$mK9!wQ2*vR8#tL4@xN0",
    url: "https://dashboard.stripe.com/login",
    totp: "613 904",
    passwordStrength: "Strong",
    customFields: [
      { label: "Merchant ID", value: "acct_1N00ABCDEF9921" },
      { label: "Webhook Signing Secret", value: "whsec_99182abcdef0019283", concealed: true },
    ],
    createdAt: "2025-03-01 10:15",
    updatedAt: "2026-06-12 11:20",
  },
  {
    id: "item-figma-workspace",
    title: "Figma Team Space",
    category: "login",
    ownership: "personal",
    organizationId: null,
    collectionIds: [],
    folderId: "folder-personal",
    vault: "Personal",
    favorite: false,
    deletedAt: null,
    folder: "Personal",
    username: "alex.rivera@creative-mesh.io",
    password: "fG4#uM9!qP2$zX8*tW1@yB6",
    url: "https://www.figma.com/login",
    passwordStrength: "Strong",
    notes: "Design system tokens and layout specs repository.",
    createdAt: "2025-05-19 14:40",
    updatedAt: "2026-05-30 08:50",
  },
  {
    id: "item-proton-mail",
    title: "ProtonMail Secure Mailbox",
    category: "login",
    ownership: "personal",
    organizationId: null,
    collectionIds: [],
    folderId: "folder-personal",
    vault: "Personal",
    favorite: true,
    deletedAt: null,
    folder: "Personal",
    username: "alex.rivera@proton.me",
    password: "pM8!xK2#vQ9$tL5*wR1@zN7",
    url: "https://mail.proton.me/login",
    totp: "918 203",
    passwordStrength: "Very Strong",
    notes: "Primary personal encrypted communication inbox.",
    customFields: [
      { label: "Recovery Email", value: "backup-alex@fastmail.com" },
      { label: "PGP Key ID", value: "0x89AB44CD12EF7701" },
    ],
    createdAt: "2024-08-05 13:10",
    updatedAt: "2026-08-11 18:22",
  },
  {
    id: "item-cloudflare-portal",
    title: "Cloudflare Edge Portal",
    category: "login",
    ownership: "organization",
    organizationId: "organization-acme",
    collectionIds: ["collection-infrastructure"],
    folderId: "folder-infrastructure",
    vault: "Work",
    favorite: false,
    deletedAt: null,
    folder: "Infrastructure",
    username: "devops-alex@mesh.network",
    password: "cF9#tL1!wQ8$zX2*vP5@rM0",
    url: "https://dash.cloudflare.com/login",
    totp: "502 839",
    passwordStrength: "Strong",
    customFields: [
      { label: "Account ID", value: "cf-acc-77192-omega" },
      { label: "Global API Key", value: "c98f7e21a00192837465bcefa", concealed: true },
    ],
    createdAt: "2025-02-14 17:00",
    updatedAt: "2026-07-04 10:12",
  },
  {
    id: "item-tailscale-network",
    title: "Tailscale Mesh VPN",
    category: "login",
    ownership: "organization",
    organizationId: "organization-acme",
    collectionIds: ["collection-infrastructure"],
    folderId: "folder-infrastructure",
    vault: "Work",
    favorite: false,
    deletedAt: null,
    folder: "Infrastructure",
    username: "alex.rivera@tailscale.internal",
    password: "tS3$wP9!vQ1*mX8#tL5@zK2",
    url: "https://login.tailscale.com",
    totp: "729 110",
    passwordStrength: "Very Strong",
    notes: "Controls mesh access to development and staging clusters.",
    createdAt: "2025-06-20 09:30",
    updatedAt: "2026-08-22 15:40",
  },
  {
    id: "item-spotify-family",
    title: "Spotify Family Account",
    category: "login",
    ownership: "organization",
    organizationId: "organization-acme",
    collectionIds: ["collection-family"],
    folderId: "folder-family",
    vault: "Shared",
    favorite: false,
    deletedAt: null,
    folder: "Family",
    username: "rivera.family.music@gmail.com",
    password: "sP1#mK8!tQ2$vL9*wR4@xZ5",
    url: "https://accounts.spotify.com/login",
    passwordStrength: "Medium",
    notes: "Home stereo and family streaming account.",
    createdAt: "2024-05-10 20:12",
    updatedAt: "2026-04-18 19:30",
  },
  {
    id: "item-wifi-office",
    title: "Office Wi-Fi & Guest Access",
    category: "secureNote",
    ownership: "organization",
    organizationId: "organization-acme",
    collectionIds: ["collection-infrastructure"],
    folderId: "folder-infrastructure",
    vault: "Work",
    favorite: false,
    deletedAt: null,
    folder: "Infrastructure",
    notes: `Primary Staff Wi-Fi:
SSID: Acme-HQ-Secure (WPA3 Enterprise)
Radius Server: radius01.corp.internal

Guest Network:
SSID: Acme-Visitors-5G
Passphrase: crystal-meadow-summit-98
VLAN: 40 (isolated internet only)

IT Support Desk: ext 4400 / #it-helpdesk`,
    createdAt: "2025-01-10 10:00",
    updatedAt: "2026-06-01 11:00",
  },
  {
    id: "item-recovery-seed",
    title: "Hardware Wallet Master Seeds",
    category: "secureNote",
    ownership: "personal",
    organizationId: null,
    collectionIds: [],
    folderId: "folder-security",
    vault: "Personal",
    favorite: true,
    deletedAt: null,
    folder: "Security",
    notes: `Cold Storage Backup Split:
Shard 1: alpine meadow whisper glacier canyon timber
Shard 2: iron velocity thunder echo balance summit
Safety Box Location: Vault 4B, Central Deposit`,
    customFields: [
      { label: "Passphrase", value: "amber-shield-991", concealed: true },
      { label: "Hardware Model", value: "Ledger Stax v2" },
    ],
    createdAt: "2024-09-12 14:00",
    updatedAt: "2026-03-15 16:30",
  },
  {
    id: "item-home-network",
    title: "Home Gateway & Router Specs",
    category: "secureNote",
    ownership: "personal",
    organizationId: null,
    collectionIds: [],
    folderId: "folder-personal",
    vault: "Personal",
    favorite: false,
    deletedAt: null,
    folder: "Personal",
    notes: `Gateway IP: 192.168.1.1
Subnet Mask: 255.255.255.0
DNS Primary: 1.1.1.1 (Cloudflare DoH)
DNS Secondary: 9.9.9.9 (Quad9)
Admin Username: admin-local`,
    customFields: [
      { label: "Admin Password", value: "RouterGate#99201!x", concealed: true },
      { label: "PPPoE VLAN", value: "201" },
    ],
    createdAt: "2025-04-02 08:30",
    updatedAt: "2026-07-29 12:10",
  },
  {
    id: "item-corporate-card",
    title: "Acme Corporate Platinum",
    category: "creditCard",
    ownership: "organization",
    organizationId: "organization-acme",
    collectionIds: ["collection-finance"],
    folderId: "folder-finance",
    vault: "Work",
    favorite: false,
    deletedAt: null,
    folder: "Finance",
    customFields: [
      { label: "Cardholder Name", value: "Alex J. Rivera" },
      { label: "Card Number", value: "4242 •••• •••• 8819", concealed: true },
      { label: "Expiration", value: "09/29" },
      { label: "Security Code (CVV)", value: "714", concealed: true },
      { label: "PIN", value: "8821", concealed: true },
      { label: "Monthly Limit", value: "$50,000 USD" },
    ],
    notes: "Designated for cloud hosting, infrastructure SaaS, and engineering travel.",
    createdAt: "2025-01-02 09:00",
    updatedAt: "2026-08-01 10:15",
  },
  {
    id: "item-personal-sapphire",
    title: "Personal Sapphire Rewards",
    category: "creditCard",
    ownership: "personal",
    organizationId: null,
    collectionIds: [],
    folderId: "folder-finance",
    vault: "Personal",
    favorite: false,
    deletedAt: null,
    folder: "Finance",
    customFields: [
      { label: "Cardholder Name", value: "Alex Rivera" },
      { label: "Card Number", value: "4111 •••• •••• 9810", concealed: true },
      { label: "Expiration", value: "12/28" },
      { label: "Security Code (CVV)", value: "492", concealed: true },
    ],
    createdAt: "2024-07-11 15:20",
    updatedAt: "2026-05-10 14:00",
  },
  {
    id: "item-identity-work",
    title: "Alex Rivera - Engineering Profile",
    category: "identity",
    ownership: "organization",
    organizationId: "organization-acme",
    collectionIds: ["collection-identity"],
    folderId: "folder-identity",
    vault: "Work",
    favorite: false,
    deletedAt: null,
    folder: "Identity",
    customFields: [
      { label: "Full Name", value: "Alex Jordan Rivera" },
      { label: "Title", value: "Principal Systems Architect" },
      { label: "Employee ID", value: "ACME-EMP-8841" },
      { label: "Work Email", value: "alex.rivera@acme.internal" },
      { label: "Office Phone", value: "+1 (555) 019-2834" },
      { label: "Department", value: "Core Infrastructure & Security" },
    ],
    createdAt: "2025-01-05 10:30",
    updatedAt: "2026-02-20 11:45",
  },
  {
    id: "item-identity-passport",
    title: "Alex Rivera - Passport & ID",
    category: "identity",
    ownership: "personal",
    organizationId: null,
    collectionIds: [],
    folderId: "folder-personal",
    vault: "Personal",
    favorite: true,
    deletedAt: null,
    folder: "Personal",
    customFields: [
      { label: "Document Type", value: "Passport" },
      { label: "Passport Number", value: "F92830114", concealed: true },
      { label: "Nationality", value: "United States of America" },
      { label: "Date of Birth", value: "1990-06-14" },
      { label: "Date of Expiry", value: "2032-04-18" },
    ],
    createdAt: "2024-06-01 11:00",
    updatedAt: "2026-01-10 16:00",
  },
  {
    id: "item-bastion-server",
    title: "Production Bastion Gateway",
    category: "sshKey",
    ownership: "organization",
    organizationId: "organization-acme",
    collectionIds: ["collection-infrastructure"],
    folderId: "folder-infrastructure",
    vault: "Work",
    favorite: false,
    deletedAt: null,
    folder: "Infrastructure",
    username: "ec2-user",
    url: "ssh://bastion.us-east-1.acme.net:2222",
    notes: "Jump host for all VPC private subnets. Requires WireGuard tunnel + YubiKey touch.",
    customFields: [
      { label: "Host", value: "bastion.us-east-1.acme.net" },
      { label: "Port", value: "2222" },
      { label: "Private IP", value: "10.0.1.15" },
      { label: "Public IP", value: "54.210.99.18" },
    ],
    createdAt: "2025-02-10 13:00",
    updatedAt: "2026-08-14 09:30",
  },
  {
    id: "item-deploy-sshkey",
    title: "Production Deploy Key (Ed25519)",
    category: "sshKey",
    ownership: "organization",
    organizationId: "organization-acme",
    collectionIds: ["collection-engineering"],
    folderId: "folder-engineering",
    vault: "Work",
    favorite: false,
    deletedAt: null,
    folder: "Engineering",
    customFields: [
      { label: "Key Type", value: "Ed25519" },
      { label: "Fingerprint", value: "SHA256:7mP4e2xXqL99+vO21bNmKl98PqWs0192" },
      {
        label: "Public Key",
        value: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGs7z9M2K918... deploy@acme-core",
      },
      {
        label: "Passphrase",
        value: "deploy-guard#summit-2026",
        concealed: true,
      },
    ],
    notes: "Read-only deployment key for production container orchestration pull sync.",
    createdAt: "2025-03-22 15:45",
    updatedAt: "2026-07-10 14:20",
  },
]
