import { expect, test } from "bun:test"
import { serverAppCreate } from "../../src/server/serverAppCreate.js"
import { serverRouteRegistrationDrift } from "../../src/server/serverRouteRegistrationDrift.js"
import { serverRouteRegistrationIntrospect } from "../../src/server/serverRouteRegistrationIntrospect.js"

const duplicatedRouteRegistrations = [
  { basePath: "/", method: "DELETE", path: "/api/ciphers" },
  { basePath: "/", method: "DELETE", path: "/api/ciphers/:cipher_id" },
  { basePath: "/", method: "DELETE", path: "/api/ciphers/:cipher_id/admin" },
  { basePath: "/", method: "DELETE", path: "/api/ciphers/admin" },
  { basePath: "/", method: "DELETE", path: "/api/folders/:folder_id" },
  { basePath: "/", method: "DELETE", path: "/api/sends/:send_id" },
  { basePath: "/", method: "GET", path: "/api/ciphers" },
  { basePath: "/", method: "GET", path: "/api/ciphers/:cipher_id" },
  { basePath: "/", method: "GET", path: "/api/ciphers/:cipher_id/admin" },
  { basePath: "/", method: "GET", path: "/api/ciphers/:cipher_id/details" },
  { basePath: "/", method: "GET", path: "/api/folders" },
  { basePath: "/", method: "GET", path: "/api/folders/:folder_id" },
  { basePath: "/", method: "GET", path: "/api/sends" },
  { basePath: "/", method: "GET", path: "/api/sends/:send_id" },
  { basePath: "/", method: "POST", path: "/api/ciphers" },
  { basePath: "/", method: "POST", path: "/api/ciphers/:cipher_id" },
  { basePath: "/", method: "POST", path: "/api/ciphers/:cipher_id/admin" },
  { basePath: "/", method: "POST", path: "/api/ciphers/:cipher_id/delete" },
  { basePath: "/", method: "POST", path: "/api/ciphers/:cipher_id/delete-admin" },
  { basePath: "/", method: "POST", path: "/api/ciphers/:cipher_id/partial" },
  { basePath: "/", method: "POST", path: "/api/ciphers/admin" },
  { basePath: "/", method: "POST", path: "/api/ciphers/create" },
  { basePath: "/", method: "POST", path: "/api/ciphers/import" },
  { basePath: "/", method: "POST", path: "/api/ciphers/delete" },
  { basePath: "/", method: "POST", path: "/api/ciphers/delete-admin" },
  { basePath: "/", method: "POST", path: "/api/ciphers/move" },
  { basePath: "/", method: "POST", path: "/api/folders" },
  { basePath: "/", method: "POST", path: "/api/folders/:folder_id" },
  { basePath: "/", method: "POST", path: "/api/folders/:folder_id/delete" },
  { basePath: "/", method: "POST", path: "/api/sends" },
  { basePath: "/", method: "POST", path: "/api/sends/file" },
  { basePath: "/", method: "POST", path: "/api/sends/file/v2" },
  { basePath: "/", method: "POST", path: "/api/sends/:send_id/file/:file_id" },
  { basePath: "/", method: "PUT", path: "/api/ciphers/:cipher_id" },
  { basePath: "/", method: "PUT", path: "/api/ciphers/:cipher_id/admin" },
  { basePath: "/", method: "PUT", path: "/api/ciphers/:cipher_id/archive" },
  { basePath: "/", method: "PUT", path: "/api/ciphers/:cipher_id/delete" },
  { basePath: "/", method: "PUT", path: "/api/ciphers/:cipher_id/delete-admin" },
  { basePath: "/", method: "PUT", path: "/api/ciphers/:cipher_id/partial" },
  { basePath: "/", method: "PUT", path: "/api/ciphers/:cipher_id/restore" },
  { basePath: "/", method: "PUT", path: "/api/ciphers/:cipher_id/restore-admin" },
  { basePath: "/", method: "PUT", path: "/api/ciphers/:cipher_id/unarchive" },
  { basePath: "/", method: "PUT", path: "/api/ciphers/archive" },
  { basePath: "/", method: "PUT", path: "/api/ciphers/delete" },
  { basePath: "/", method: "PUT", path: "/api/ciphers/delete-admin" },
  { basePath: "/", method: "PUT", path: "/api/ciphers/move" },
  { basePath: "/", method: "PUT", path: "/api/ciphers/restore" },
  { basePath: "/", method: "PUT", path: "/api/ciphers/restore-admin" },
  { basePath: "/", method: "PUT", path: "/api/ciphers/unarchive" },
  { basePath: "/", method: "PUT", path: "/api/folders/:folder_id" },
  { basePath: "/", method: "PUT", path: "/api/sends/:send_id" },
  { basePath: "/", method: "PUT", path: "/api/sends/:send_id/remove-password" },
].flatMap((registration) => [registration, registration])

const duplicatedEmergencyAccessRouteRegistrations = [
  { basePath: "/", method: "DELETE", path: "/api/emergency-access/:emer_id" },
  { basePath: "/", method: "GET", path: "/api/emergency-access/:emer_id" },
  { basePath: "/", method: "GET", path: "/api/emergency-access/:emer_id/policies" },
  { basePath: "/", method: "GET", path: "/api/emergency-access/granted" },
  { basePath: "/", method: "GET", path: "/api/emergency-access/trusted" },
  { basePath: "/", method: "POST", path: "/api/emergency-access/:emer_id" },
  { basePath: "/", method: "POST", path: "/api/emergency-access/:emer_id/accept" },
  { basePath: "/", method: "POST", path: "/api/emergency-access/:emer_id/approve" },
  { basePath: "/", method: "POST", path: "/api/emergency-access/:emer_id/confirm" },
  { basePath: "/", method: "POST", path: "/api/emergency-access/:emer_id/delete" },
  { basePath: "/", method: "POST", path: "/api/emergency-access/:emer_id/initiate" },
  { basePath: "/", method: "POST", path: "/api/emergency-access/:emer_id/password" },
  { basePath: "/", method: "POST", path: "/api/emergency-access/:emer_id/reinvite" },
  { basePath: "/", method: "POST", path: "/api/emergency-access/:emer_id/reject" },
  { basePath: "/", method: "POST", path: "/api/emergency-access/:emer_id/takeover" },
  { basePath: "/", method: "POST", path: "/api/emergency-access/:emer_id/view" },
  { basePath: "/", method: "POST", path: "/api/emergency-access/invite" },
  { basePath: "/", method: "PUT", path: "/api/emergency-access/:emer_id" },
].flatMap((registration) => [registration, registration])

const duplicatedTwoFactorRouteRegistrations = [
  { basePath: "/", method: "DELETE", path: "/api/two-factor/authenticator" },
  { basePath: "/", method: "DELETE", path: "/api/two-factor/webauthn" },
  { basePath: "/", method: "GET", path: "/api/two-factor" },
  { basePath: "/", method: "GET", path: "/api/two-factor/get-device-verification-settings" },
  { basePath: "/", method: "POST", path: "/api/accounts/request-otp" },
  { basePath: "/", method: "POST", path: "/api/accounts/verify-otp" },
  { basePath: "/", method: "POST", path: "/api/two-factor/authenticator" },
  { basePath: "/", method: "POST", path: "/api/two-factor/disable" },
  { basePath: "/", method: "POST", path: "/api/two-factor/duo" },
  { basePath: "/", method: "POST", path: "/api/two-factor/get-authenticator" },
  { basePath: "/", method: "POST", path: "/api/two-factor/get-duo" },
  { basePath: "/", method: "POST", path: "/api/two-factor/get-email" },
  { basePath: "/", method: "POST", path: "/api/two-factor/get-recover" },
  { basePath: "/", method: "POST", path: "/api/two-factor/get-webauthn" },
  { basePath: "/", method: "POST", path: "/api/two-factor/get-webauthn-challenge" },
  { basePath: "/", method: "POST", path: "/api/two-factor/get-yubikey" },
  { basePath: "/", method: "POST", path: "/api/two-factor/send-email" },
  { basePath: "/", method: "POST", path: "/api/two-factor/webauthn" },
  { basePath: "/", method: "POST", path: "/api/two-factor/yubikey" },
  { basePath: "/", method: "PUT", path: "/api/two-factor/authenticator" },
  { basePath: "/", method: "PUT", path: "/api/two-factor/disable" },
  { basePath: "/", method: "PUT", path: "/api/two-factor/duo" },
  { basePath: "/", method: "PUT", path: "/api/two-factor/email" },
  { basePath: "/", method: "PUT", path: "/api/two-factor/webauthn" },
  { basePath: "/", method: "PUT", path: "/api/two-factor/yubikey" },
].flatMap((registration) => [registration, registration])

const currentRouteRegistrations = [
  ...[{ basePath: "/", method: "GET", path: "/api/collections" }].flatMap((registration) => [
    registration,
    registration,
  ]),
  ...[
    { basePath: "/", method: "DELETE", path: "/api/organizations/:org_id/collections" },
    { basePath: "/", method: "DELETE", path: "/api/organizations/:org_id/collections/:col_id" },
    { basePath: "/", method: "GET", path: "/api/organizations/:org_id/collections" },
    { basePath: "/", method: "GET", path: "/api/organizations/:org_id/collections/:col_id/details" },
    { basePath: "/", method: "GET", path: "/api/organizations/:org_id/collections/:col_id/users" },
    { basePath: "/", method: "GET", path: "/api/organizations/:org_id/collections/details" },
    { basePath: "/", method: "POST", path: "/api/organizations/:org_id/collections" },
    { basePath: "/", method: "POST", path: "/api/organizations/:org_id/collections/:col_id" },
    { basePath: "/", method: "POST", path: "/api/organizations/:org_id/collections/:col_id/delete" },
    { basePath: "/", method: "POST", path: "/api/organizations/:org_id/collections/bulk-access" },
    { basePath: "/", method: "PUT", path: "/api/organizations/:org_id/collections/:col_id" },
  ].flatMap((registration) => [registration, registration, registration]),
  ...[
    { basePath: "/", method: "GET", path: "/api/ciphers/:cipher_id/attachment/:attachment_id" },
    { basePath: "/", method: "POST", path: "/api/ciphers/:cipher_id/attachment/v2" },
    { basePath: "/", method: "POST", path: "/api/ciphers/:cipher_id/attachment/:attachment_id" },
    { basePath: "/", method: "POST", path: "/api/ciphers/:cipher_id/attachment" },
    { basePath: "/", method: "POST", path: "/api/ciphers/:cipher_id/attachment-admin" },
    { basePath: "/", method: "POST", path: "/api/ciphers/:cipher_id/attachment/:attachment_id/share" },
    {
      basePath: "/",
      method: "POST",
      path: "/api/ciphers/:cipher_id/attachment/:attachment_id/delete-admin",
    },
    { basePath: "/", method: "POST", path: "/api/ciphers/:cipher_id/attachment/:attachment_id/delete" },
    { basePath: "/", method: "DELETE", path: "/api/ciphers/:cipher_id/attachment/:attachment_id" },
    { basePath: "/", method: "DELETE", path: "/api/ciphers/:cipher_id/attachment/:attachment_id/admin" },
  ].flatMap((registration) => [registration, registration]),
  { basePath: "/", method: "GET", path: "/api/sends/:send_id/:file_id" },
  { basePath: "/", method: "DELETE", path: "/api/accounts" },
  { basePath: "/", method: "DELETE", path: "/api/accounts" },
  { basePath: "/", method: "GET", path: "/api/accounts/profile" },
  { basePath: "/", method: "GET", path: "/api/accounts/profile" },
  { basePath: "/", method: "GET", path: "/api/accounts/revision-date" },
  { basePath: "/", method: "GET", path: "/api/accounts/revision-date" },
  { basePath: "/", method: "GET", path: "/api/devices" },
  { basePath: "/", method: "GET", path: "/api/devices" },
  { basePath: "/", method: "GET", path: "/api/devices/identifier/:device_id" },
  { basePath: "/", method: "GET", path: "/api/devices/identifier/:device_id" },
  { basePath: "/", method: "GET", path: "/api/devices/knowndevice" },
  { basePath: "/", method: "GET", path: "/api/settings/domains" },
  { basePath: "/", method: "GET", path: "/api/settings/domains" },
  { basePath: "/", method: "GET", path: "/api/sync" },
  { basePath: "/", method: "GET", path: "/api/sync" },
  { basePath: "/", method: "GET", path: "/api/users/:user_id/public-key" },
  { basePath: "/", method: "GET", path: "/api/users/:user_id/public-key" },
  { basePath: "/", method: "GET", path: "/api/organizations/:org_id/keys" },
  { basePath: "/", method: "GET", path: "/api/organizations/:org_id/keys" },
  { basePath: "/", method: "GET", path: "/api/organizations/:org_id/keys" },
  { basePath: "/", method: "GET", path: "/api/organizations/:org_id/public-key" },
  { basePath: "/", method: "GET", path: "/api/organizations/:org_id/public-key" },
  { basePath: "/", method: "GET", path: "/api/organizations/:org_id/public-key" },
  { basePath: "/", method: "GET", path: "/api/organizations/:org_id" },
  { basePath: "/", method: "GET", path: "/api/organizations/:org_id" },
  { basePath: "/", method: "GET", path: "/api/organizations/:org_id" },
  { basePath: "/", method: "GET", path: "/api/organizations/:org_id/export" },
  { basePath: "/", method: "GET", path: "/api/organizations/:org_id/export" },
  { basePath: "/", method: "GET", path: "/api/organizations/:org_id/export" },
  ...duplicatedRouteRegistrations,
  ...duplicatedEmergencyAccessRouteRegistrations,
  ...duplicatedTwoFactorRouteRegistrations,
  { basePath: "/", method: "GET", path: "/" },
  { basePath: "/", method: "GET", path: "/*" },
  { basePath: "/", method: "GET", path: "/.well-known/apple-app-site-association" },
  { basePath: "/", method: "GET", path: "/admin/" },
  { basePath: "/", method: "GET", path: "/alive" },
  { basePath: "/", method: "GET", path: "/api/alive" },
  { basePath: "/", method: "GET", path: "/api/config" },
  { basePath: "/", method: "GET", path: "/api/now" },
  { basePath: "/", method: "GET", path: "/api/plans" },
  { basePath: "/", method: "GET", path: "/api/organizations/:_org_id/billing/metadata" },
  { basePath: "/", method: "GET", path: "/api/organizations/:_org_id/billing/metadata" },
  { basePath: "/", method: "GET", path: "/api/organizations/:_org_id/billing/metadata" },
  { basePath: "/", method: "GET", path: "/api/organizations/:_org_id/billing/vnext/self-host/metadata" },
  { basePath: "/", method: "GET", path: "/api/organizations/:_org_id/billing/vnext/self-host/metadata" },
  { basePath: "/", method: "GET", path: "/api/organizations/:_org_id/billing/vnext/self-host/metadata" },
  { basePath: "/", method: "GET", path: "/api/organizations/:_org_id/billing/vnext/warnings" },
  { basePath: "/", method: "GET", path: "/api/organizations/:_org_id/billing/vnext/warnings" },
  { basePath: "/", method: "GET", path: "/api/organizations/:_org_id/billing/vnext/warnings" },
  { basePath: "/", method: "GET", path: "/api/version" },
  { basePath: "/", method: "GET", path: "/api/webauthn" },
  { basePath: "/", method: "GET", path: "/app-id.json" },
  { basePath: "/", method: "GET", path: "/attachments/:cipher_id/:file_id" },
  { basePath: "/", method: "GET", path: "/css/vaultwarden.css" },
  { basePath: "/", method: "GET", path: "/health" },
  { basePath: "/", method: "GET", path: "/icons/:host/icon.png" },
  { basePath: "/", method: "GET", path: "/identity/connect/authorize" },
  { basePath: "/", method: "GET", path: "/identity/connect/oidc-signin" },
  { basePath: "/", method: "GET", path: "/identity/sso/prevalidate" },
  { basePath: "/", method: "GET", path: "/notifications/anonymous-hub" },
  { basePath: "/", method: "GET", path: "/notifications/hub" },
  { basePath: "/", method: "POST", path: "/api/sends/access" },
  { basePath: "/", method: "POST", path: "/api/sends/access/:access_id" },
  { basePath: "/", method: "POST", path: "/api/sends/access/file/:file_id" },
  { basePath: "/", method: "POST", path: "/api/sends/:send_id/access/file/:file_id" },
  { basePath: "/", method: "POST", path: "/api/accounts/api-key" },
  { basePath: "/", method: "POST", path: "/api/accounts/api-key" },
  { basePath: "/", method: "POST", path: "/api/accounts/delete" },
  { basePath: "/", method: "POST", path: "/api/accounts/delete" },
  { basePath: "/", method: "POST", path: "/api/accounts/delete-recover" },
  { basePath: "/", method: "POST", path: "/api/accounts/delete-recover-token" },
  { basePath: "/", method: "POST", path: "/api/accounts/email" },
  { basePath: "/", method: "POST", path: "/api/accounts/email" },
  { basePath: "/", method: "POST", path: "/api/accounts/email-token" },
  { basePath: "/", method: "POST", path: "/api/accounts/email-token" },
  { basePath: "/", method: "POST", path: "/api/accounts/kdf" },
  { basePath: "/", method: "POST", path: "/api/accounts/kdf" },
  { basePath: "/", method: "POST", path: "/api/accounts/key-management/rotate-user-account-keys" },
  { basePath: "/", method: "POST", path: "/api/accounts/key-management/rotate-user-account-keys" },
  { basePath: "/", method: "POST", path: "/api/accounts/keys" },
  { basePath: "/", method: "POST", path: "/api/accounts/keys" },
  { basePath: "/", method: "POST", path: "/api/accounts/password" },
  { basePath: "/", method: "POST", path: "/api/accounts/password" },
  { basePath: "/", method: "POST", path: "/api/accounts/password-hint" },
  { basePath: "/", method: "POST", path: "/api/accounts/prelogin" },
  { basePath: "/", method: "POST", path: "/api/accounts/profile" },
  { basePath: "/", method: "POST", path: "/api/accounts/profile" },
  { basePath: "/", method: "POST", path: "/api/accounts/rotate-api-key" },
  { basePath: "/", method: "POST", path: "/api/accounts/rotate-api-key" },
  { basePath: "/", method: "POST", path: "/api/accounts/security-stamp" },
  { basePath: "/", method: "POST", path: "/api/accounts/security-stamp" },
  { basePath: "/", method: "POST", path: "/api/accounts/set-password" },
  { basePath: "/", method: "POST", path: "/api/accounts/set-password" },
  { basePath: "/", method: "POST", path: "/api/accounts/verify-email" },
  { basePath: "/", method: "POST", path: "/api/accounts/verify-email" },
  { basePath: "/", method: "POST", path: "/api/accounts/verify-email-token" },
  { basePath: "/", method: "POST", path: "/api/accounts/verify-password" },
  { basePath: "/", method: "POST", path: "/api/accounts/verify-password" },
  { basePath: "/", method: "POST", path: "/api/devices/identifier/:device_id/clear-token" },
  { basePath: "/", method: "POST", path: "/api/devices/identifier/:device_id/token" },
  { basePath: "/", method: "POST", path: "/api/devices/identifier/:device_id/token" },
  { basePath: "/", method: "POST", path: "/api/settings/domains" },
  { basePath: "/", method: "POST", path: "/api/settings/domains" },
  { basePath: "/", method: "POST", path: "/api/public/organization/import" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/users/public-keys" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/users/public-keys" },
  { basePath: "/", method: "POST", path: "/api/two-factor/send-email-login" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/users/public-keys" },
  { basePath: "/", method: "POST", path: "/api/organizations" },
  { basePath: "/", method: "POST", path: "/api/organizations" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/delete" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/delete" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/delete" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/keys" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/keys" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/keys" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/api-key" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/api-key" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/api-key" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/leave" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/leave" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/leave" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/rotate-api-key" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/rotate-api-key" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/rotate-api-key" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/users/invite" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/users/invite" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/users/invite" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/users/:member_id/accept" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/users/:member_id/accept" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/users/:member_id/confirm" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/users/:member_id/confirm" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/users/:member_id/confirm" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/users/:member_id/reinvite" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/users/:member_id/reinvite" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/users/:member_id/reinvite" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/users/confirm" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/users/confirm" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/users/confirm" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/users/reinvite" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/users/reinvite" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/users/reinvite" },
  { basePath: "/", method: "GET", path: "/api/organizations/:org_id/users" },
  { basePath: "/", method: "GET", path: "/api/organizations/:org_id/users" },
  { basePath: "/", method: "GET", path: "/api/organizations/:org_id/users" },
  { basePath: "/", method: "GET", path: "/api/organizations/:org_id/users/mini-details" },
  { basePath: "/", method: "GET", path: "/api/organizations/:org_id/users/mini-details" },
  { basePath: "/", method: "GET", path: "/api/organizations/:org_id/users/mini-details" },
  { basePath: "/", method: "GET", path: "/api/organizations/:org_id/users/:member_id" },
  { basePath: "/", method: "GET", path: "/api/organizations/:org_id/users/:member_id" },
  { basePath: "/", method: "GET", path: "/api/organizations/:org_id/users/:member_id" },
  { basePath: "/", method: "PUT", path: "/api/organizations/:org_id/users/:member_id" },
  { basePath: "/", method: "PUT", path: "/api/organizations/:org_id/users/:member_id" },
  { basePath: "/", method: "PUT", path: "/api/organizations/:org_id/users/:member_id" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/users/:member_id" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/users/:member_id" },
  { basePath: "/", method: "POST", path: "/api/organizations/:org_id/users/:member_id" },
  { basePath: "/", method: "DELETE", path: "/api/organizations/:org_id/users" },
  { basePath: "/", method: "DELETE", path: "/api/organizations/:org_id/users" },
  { basePath: "/", method: "DELETE", path: "/api/organizations/:org_id/users" },
  { basePath: "/", method: "DELETE", path: "/api/organizations/:org_id/users/:member_id" },
  { basePath: "/", method: "DELETE", path: "/api/organizations/:org_id/users/:member_id" },
  { basePath: "/", method: "DELETE", path: "/api/organizations/:org_id/users/:member_id" },
  { basePath: "/", method: "PUT", path: "/api/organizations/:org_id/users/:member_id/revoke" },
  { basePath: "/", method: "PUT", path: "/api/organizations/:org_id/users/:member_id/revoke" },
  { basePath: "/", method: "PUT", path: "/api/organizations/:org_id/users/:member_id/revoke" },
  { basePath: "/", method: "PUT", path: "/api/organizations/:org_id/users/revoke" },
  { basePath: "/", method: "PUT", path: "/api/organizations/:org_id/users/revoke" },
  { basePath: "/", method: "PUT", path: "/api/organizations/:org_id/users/revoke" },
  { basePath: "/", method: "PUT", path: "/api/organizations/:org_id/users/:member_id/restore/vnext" },
  { basePath: "/", method: "PUT", path: "/api/organizations/:org_id/users/:member_id/restore/vnext" },
  { basePath: "/", method: "PUT", path: "/api/organizations/:org_id/users/:member_id/restore/vnext" },
  { basePath: "/", method: "PUT", path: "/api/organizations/:org_id/users/:member_id/restore" },
  { basePath: "/", method: "PUT", path: "/api/organizations/:org_id/users/:member_id/restore" },
  { basePath: "/", method: "PUT", path: "/api/organizations/:org_id/users/:member_id/restore" },
  { basePath: "/", method: "PUT", path: "/api/organizations/:org_id/users/restore" },
  { basePath: "/", method: "PUT", path: "/api/organizations/:org_id/users/restore" },
  { basePath: "/", method: "PUT", path: "/api/organizations/:org_id/users/restore" },
  { basePath: "/", method: "DELETE", path: "/api/organizations/:org_id" },
  { basePath: "/", method: "DELETE", path: "/api/organizations/:org_id" },
  { basePath: "/", method: "DELETE", path: "/api/organizations/:org_id" },
  { basePath: "/", method: "POST", path: "/identity/accounts/prelogin" },
  { basePath: "/", method: "POST", path: "/identity/accounts/prelogin/password" },
  { basePath: "/", method: "POST", path: "/identity/accounts/register" },
  { basePath: "/", method: "POST", path: "/identity/accounts/register/finish" },
  { basePath: "/", method: "POST", path: "/identity/accounts/register/send-verification-email" },
  { basePath: "/", method: "POST", path: "/identity/connect/token" },
  { basePath: "/", method: "PUT", path: "/api/accounts/avatar" },
  { basePath: "/", method: "PUT", path: "/api/accounts/avatar" },
  { basePath: "/", method: "PUT", path: "/api/accounts/profile" },
  { basePath: "/", method: "PUT", path: "/api/accounts/profile" },
  { basePath: "/", method: "PUT", path: "/api/devices/identifier/:device_id/clear-token" },
  { basePath: "/", method: "PUT", path: "/api/settings/domains" },
  { basePath: "/", method: "PUT", path: "/api/settings/domains" },
  { basePath: "/", method: "PUT", path: "/api/devices/identifier/:device_id/token" },
  { basePath: "/", method: "PUT", path: "/api/devices/identifier/:device_id/token" },
  { basePath: "/", method: "PUT", path: "/api/organizations/:org_id" },
  { basePath: "/", method: "PUT", path: "/api/organizations/:org_id" },
  { basePath: "/", method: "PUT", path: "/api/organizations/:org_id" },
  { basePath: "/", method: "GET", path: "/index.html" },
  { basePath: "/", method: "GET", path: "/vw_static/:filename" },
  { basePath: "/", method: "HEAD", path: "/" },
  { basePath: "/", method: "HEAD", path: "/alive" },
].sort(serverRouteRegistrationCompare)

function serverRouteRegistrationCompare(
  left: { basePath: string; method: string; path: string },
  right: { basePath: string; method: string; path: string },
): number {
  return `${left.method} ${left.basePath}${left.path}`.localeCompare(`${right.method} ${right.basePath}${right.path}`)
}

test("serverAppCreate route registrations match the current compatibility baseline", () => {
  const registrations = serverRouteRegistrationIntrospect(serverAppCreate())

  expect([...registrations].sort(serverRouteRegistrationCompare)).toEqual(currentRouteRegistrations)
  expect(serverRouteRegistrationDrift(registrations, currentRouteRegistrations)).toEqual({ extra: [], missing: [] })
})

test("route-registration drift rejects an unplanned route even when its path is upstream-compatible", () => {
  const app = serverAppCreate()
  app.get("/api/ciphers", (context) => context.json({}))

  const registrations = serverRouteRegistrationIntrospect(app)
  expect(serverRouteRegistrationDrift(registrations, currentRouteRegistrations)).toEqual({
    extra: [{ basePath: "/", method: "GET", path: "/api/ciphers" }],
    missing: [],
  })
})
