import type { Organization } from "../schemas/organizationSchema.js"
import type { OrganizationMember } from "../schemas/organizationMemberSchema.js"
import type { OrganizationCollection } from "../schemas/organizationCollectionSchema.js"
import type { OrganizationGroup } from "../schemas/organizationGroupSchema.js"
import type { OrganizationPolicy } from "../schemas/organizationPolicySchema.js"
import type { OrganizationEvent } from "../schemas/organizationEventSchema.js"
import type { OrganizationDomain } from "../schemas/organizationDomainSchema.js"
import type { OrganizationSso } from "../schemas/organizationSsoSchema.js"
import { organizationMemberRole } from "../schemas/organizationMemberRole.js"
import { organizationMemberStatus } from "../schemas/organizationMemberStatus.js"

export interface OrganizationDemoState {
  collections: OrganizationCollection[]
  domains: OrganizationDomain[]
  events: OrganizationEvent[]
  groups: OrganizationGroup[]
  members: OrganizationMember[]
  organizations: Organization[]
  policies: OrganizationPolicy[]
  sso: OrganizationSso
}

export const organizationDemoData: OrganizationDemoState = {
  organizations: [
    {
      billingEmail: "admin@acme-corp.internal",
      hasPublicAndPrivateKeys: true,
      id: "org-acme-corp-001",
      identifier: "acme-corp",
      key: "0|acme-corp-key",
      maxCollections: 100,
      maxStorageGb: 10,
      name: "Acme Corporation",
      planType: 6,
      seats: 25,
      status: 2,
      type: 0,
    },
    {
      billingEmail: "ops@startup-lab.io",
      hasPublicAndPrivateKeys: true,
      id: "org-startup-lab-002",
      identifier: "startup-lab",
      key: "0|startup-lab-key",
      maxCollections: 20,
      maxStorageGb: 5,
      name: "Startup Lab",
      planType: 6,
      seats: 10,
      status: 2,
      type: 1,
    },
  ],
  collections: [
    {
      externalId: "COL-ENG",
      hidePasswords: false,
      id: "col-engineering-001",
      manage: true,
      manageAll: true,
      name: "Engineering Infrastructure",
      organizationId: "org-acme-corp-001",
      readOnly: false,
      users: [
        {
          hidePasswords: false,
          id: "mem-alice-001",
          manage: true,
          name: "Alice Wright",
          readOnly: false,
        },
        {
          hidePasswords: false,
          id: "mem-bob-002",
          manage: false,
          name: "Bob Stone",
          readOnly: false,
        },
      ],
    },
    {
      externalId: "COL-FIN",
      hidePasswords: false,
      id: "col-finance-002",
      manage: true,
      manageAll: false,
      name: "Finance & Banking",
      organizationId: "org-acme-corp-001",
      readOnly: false,
      users: [
        {
          hidePasswords: false,
          id: "mem-carol-003",
          manage: true,
          name: "Carol Danvers",
          readOnly: false,
        },
      ],
    },
    {
      externalId: "COL-MKT",
      hidePasswords: false,
      id: "col-marketing-003",
      manage: true,
      manageAll: false,
      name: "Marketing & Social",
      organizationId: "org-acme-corp-001",
      readOnly: false,
      users: [],
    },
  ],
  members: [
    {
      accessAll: true,
      collections: [],
      email: "alice.wright@acme-corp.internal",
      externalId: "EMP-001",
      id: "mem-alice-001",
      name: "Alice Wright",
      status: organizationMemberStatus.confirmed,
      twoFactorEnabled: true,
      type: organizationMemberRole.owner,
      userId: "usr-alice-001",
    },
    {
      accessAll: false,
      collections: [
        {
          hidePasswords: false,
          id: "col-engineering-001",
          manage: false,
          name: "Engineering Infrastructure",
          readOnly: false,
        },
      ],
      email: "bob.stone@acme-corp.internal",
      externalId: "EMP-002",
      id: "mem-bob-002",
      name: "Bob Stone",
      status: organizationMemberStatus.confirmed,
      twoFactorEnabled: true,
      type: organizationMemberRole.admin,
      userId: "usr-bob-002",
    },
    {
      accessAll: false,
      collections: [
        {
          hidePasswords: false,
          id: "col-finance-002",
          manage: true,
          name: "Finance & Banking",
          readOnly: false,
        },
      ],
      email: "carol.danvers@acme-corp.internal",
      externalId: "EMP-003",
      id: "mem-carol-003",
      name: "Carol Danvers",
      status: organizationMemberStatus.confirmed,
      twoFactorEnabled: false,
      type: organizationMemberRole.manager,
      userId: "usr-carol-003",
    },
    {
      accessAll: false,
      collections: [],
      email: "dave.miller@acme-corp.internal",
      externalId: null,
      id: "mem-dave-004",
      name: "Dave Miller",
      status: organizationMemberStatus.invited,
      twoFactorEnabled: false,
      type: organizationMemberRole.user,
      userId: null,
    },
  ],
  groups: [
    {
      accessAll: true,
      collections: [],
      externalId: "GRP-CORE-ENG",
      id: "grp-engineering-001",
      name: "Core Engineering Team",
      organizationId: "org-acme-corp-001",
      users: ["mem-alice-001", "mem-bob-002"],
    },
    {
      accessAll: false,
      collections: [
        {
          hidePasswords: false,
          id: "col-finance-002",
          manage: true,
          name: "Finance & Banking",
          readOnly: false,
        },
      ],
      externalId: "GRP-FIN-OPS",
      id: "grp-finance-002",
      name: "Finance Operations",
      organizationId: "org-acme-corp-001",
      users: ["mem-carol-003"],
    },
  ],
  policies: [
    {
      data: null,
      enabled: true,
      id: "pol-2fa-001",
      organizationId: "org-acme-corp-001",
      revisionDate: "2026-08-01T12:00:00.000Z",
      type: 0,
    },
    {
      data: {
        minComplexity: 3,
        minLength: 14,
        requireLower: true,
        requireNumber: true,
        requireSpecial: true,
        requireUpper: true,
      },
      enabled: true,
      id: "pol-masterpass-002",
      organizationId: "org-acme-corp-001",
      revisionDate: "2026-08-01T12:00:00.000Z",
      type: 1,
    },
    {
      data: { defaultLength: 20, useLower: true, useNumbers: true, useSpecial: true, useUpper: true },
      enabled: true,
      id: "pol-passgen-003",
      organizationId: "org-acme-corp-001",
      revisionDate: "2026-08-01T12:00:00.000Z",
      type: 2,
    },
    {
      data: null,
      enabled: false,
      id: "pol-singleorg-004",
      organizationId: "org-acme-corp-001",
      revisionDate: "2026-08-01T12:00:00.000Z",
      type: 3,
    },
    {
      data: null,
      enabled: false,
      id: "pol-personal-005",
      organizationId: "org-acme-corp-001",
      revisionDate: "2026-08-01T12:00:00.000Z",
      type: 5,
    },
    {
      data: null,
      enabled: false,
      id: "pol-disablesend-006",
      organizationId: "org-acme-corp-001",
      revisionDate: "2026-08-01T12:00:00.000Z",
      type: 6,
    },
    {
      data: { maxExpirationDays: 7 },
      enabled: true,
      id: "pol-sendopts-007",
      organizationId: "org-acme-corp-001",
      revisionDate: "2026-08-01T12:00:00.000Z",
      type: 7,
    },
    {
      canToggleState: true,
      data: null,
      enabled: true,
      id: "pol-resetpass-008",
      organizationId: "org-acme-corp-001",
      revisionDate: "2026-08-01T12:00:00.000Z",
      type: 8,
    },
    {
      data: null,
      enabled: false,
      id: "pol-pin-009",
      organizationId: "org-acme-corp-001",
      revisionDate: "2026-08-01T12:00:00.000Z",
      type: 14,
    },
    {
      data: { disallowedTypes: [] },
      enabled: false,
      id: "pol-restricted-010",
      organizationId: "org-acme-corp-001",
      revisionDate: "2026-08-01T12:00:00.000Z",
      type: 15,
    },
    {
      data: { defaultMatch: 0 },
      enabled: false,
      id: "pol-urimatch-011",
      organizationId: "org-acme-corp-001",
      revisionDate: "2026-08-01T12:00:00.000Z",
      type: 16,
    },
  ],
  events: [
    {
      actingUserId: "usr-alice-001",
      cipherId: null,
      collectionId: null,
      date: "2026-08-28T14:32:00.000Z",
      deviceType: 14,
      groupId: null,
      ipAddress: "192.168.1.100",
      organizationId: "org-acme-corp-001",
      organizationUserId: null,
      policyId: null,
      providerId: null,
      providerOrganizationId: null,
      providerUserId: null,
      type: 1000,
      userId: "usr-alice-001",
    },
    {
      actingUserId: "usr-bob-002",
      cipherId: "ciph-prod-db-001",
      collectionId: "col-engineering-001",
      date: "2026-08-28T12:15:20.000Z",
      deviceType: 1,
      groupId: null,
      ipAddress: "192.168.1.105",
      organizationId: "org-acme-corp-001",
      organizationUserId: null,
      policyId: null,
      providerId: null,
      providerOrganizationId: null,
      providerUserId: null,
      type: 1100,
      userId: "usr-bob-002",
    },
    {
      actingUserId: "usr-alice-001",
      cipherId: null,
      collectionId: null,
      date: "2026-08-27T09:40:00.000Z",
      deviceType: 14,
      groupId: null,
      ipAddress: "192.168.1.100",
      organizationId: "org-acme-corp-001",
      organizationUserId: "mem-dave-004",
      policyId: null,
      providerId: null,
      providerOrganizationId: null,
      providerUserId: null,
      type: 1500,
      userId: "usr-alice-001",
    },
  ],
  domains: [
    {
      creationDate: "2026-08-01T10:00:00.000Z",
      domainName: "acme-corp.internal",
      id: "dom-acme-001",
      jobRunCount: 1,
      lastCheckedDate: "2026-08-01T10:05:00.000Z",
      nextRunDate: null,
      organizationId: "org-acme-corp-001",
      txt: "onewarden-domain-verification=7b4fa818-f682-411a-85d9-482f3479a950",
      verifiedDate: "2026-08-01T10:05:00.000Z",
    },
    {
      creationDate: "2026-08-15T15:30:00.000Z",
      domainName: "acme.io",
      id: "dom-acme-002",
      jobRunCount: 0,
      lastCheckedDate: null,
      nextRunDate: "2026-08-30T15:30:00.000Z",
      organizationId: "org-acme-corp-001",
      txt: "onewarden-domain-verification=d32a19b8-18e4-4110-85f2-95724128f731",
      verifiedDate: null,
    },
  ],
  sso: {
    Data: {
      AllowUnsolicitedSso: true,
      Authority: "https://login.microsoftonline.com/common/v2.0",
      ClientId: "00000000-0000-0000-0000-000000000000",
      ClientSecret: "********",
      Key: null,
      MetadataAddress: "https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration",
      SsoType: 1,
    },
    Enabled: false,
    Identifier: "acme-corp",
    Urls: {
      CallbackPath: "https://vault.acme-corp.internal/oidc-signin",
      SignedOutCallbackPath: "https://vault.acme-corp.internal/oidc-signedout",
      SpAcsUrl: "https://vault.acme-corp.internal/saml2/org-acme-corp-001/Acs",
      SpEntityId: "https://vault.acme-corp.internal/saml2/org-acme-corp-001",
      SpEntityIdStatic: "https://vault.acme-corp.internal/saml2",
      SpMetadataUrl: "https://vault.acme-corp.internal/saml2/org-acme-corp-001",
    },
  },
}
