import type { IdentityConfig } from "./identityConfigSchema.js"

export function identityConfigCreate(overrides?: Partial<IdentityConfig>): IdentityConfig {
  return {
    SIGNUPS_ALLOWED: overrides?.SIGNUPS_ALLOWED ?? true,
    SIGNUPS_VERIFY: overrides?.SIGNUPS_VERIFY ?? false,
    SIGNUPS_VERIFY_RESEND_TIME: overrides?.SIGNUPS_VERIFY_RESEND_TIME ?? 3_600,
    SIGNUPS_VERIFY_RESEND_LIMIT: overrides?.SIGNUPS_VERIFY_RESEND_LIMIT ?? 6,
    SIGNUPS_DOMAINS_WHITELIST: overrides?.SIGNUPS_DOMAINS_WHITELIST ?? "",
    INVITATIONS_ALLOWED: overrides?.INVITATIONS_ALLOWED ?? true,
    INVITATION_EXPIRATION_HOURS: overrides?.INVITATION_EXPIRATION_HOURS ?? 120,
    EMERGENCY_ACCESS_ALLOWED: overrides?.EMERGENCY_ACCESS_ALLOWED ?? true,
    EMAIL_CHANGE_ALLOWED: overrides?.EMAIL_CHANGE_ALLOWED ?? true,
    PASSWORD_ITERATIONS: overrides?.PASSWORD_ITERATIONS ?? 600_000,
    PASSWORD_HINTS_ALLOWED: overrides?.PASSWORD_HINTS_ALLOWED ?? true,
    SHOW_PASSWORD_HINT: overrides?.SHOW_PASSWORD_HINT ?? false,
    MAIL_ENABLED: overrides?.MAIL_ENABLED ?? false,
    SSO_ENABLED: overrides?.SSO_ENABLED ?? false,
    SSO_ONLY: overrides?.SSO_ONLY ?? false,
    SSO_SIGNUPS_MATCH_EMAIL: overrides?.SSO_SIGNUPS_MATCH_EMAIL ?? true,
    SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION: overrides?.SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION ?? false,
    SSO_CLIENT_ID: overrides?.SSO_CLIENT_ID ?? "",
    SSO_CLIENT_SECRET: overrides?.SSO_CLIENT_SECRET ?? "",
    SSO_AUTHORITY: overrides?.SSO_AUTHORITY ?? "",
    SSO_SCOPES: overrides?.SSO_SCOPES ?? "email profile",
    SSO_AUTHORIZE_EXTRA_PARAMS: overrides?.SSO_AUTHORIZE_EXTRA_PARAMS ?? "",
    SSO_PKCE: overrides?.SSO_PKCE ?? true,
    SSO_AUTH_ONLY_NOT_SESSION: overrides?.SSO_AUTH_ONLY_NOT_SESSION ?? false,
    DISABLE_2FA_REMEMBER: overrides?.DISABLE_2FA_REMEMBER ?? false,
    UNAUTHENTICATED_RATELIMIT_SECONDS: overrides?.UNAUTHENTICATED_RATELIMIT_SECONDS ?? 60,
    UNAUTHENTICATED_RATELIMIT_MAX_BURST: overrides?.UNAUTHENTICATED_RATELIMIT_MAX_BURST ?? 50,
  }
}
