import type { IdentityConfig } from "./identityConfigSchema.js"

export function identityConfigCreate(overrides?: Partial<IdentityConfig>): IdentityConfig {
  return {
    SIGNUPS_ALLOWED: overrides?.SIGNUPS_ALLOWED ?? true,
    SIGNUPS_VERIFY: overrides?.SIGNUPS_VERIFY ?? false,
    SIGNUPS_VERIFY_RESEND_TIME: overrides?.SIGNUPS_VERIFY_RESEND_TIME ?? 3_600,
    SIGNUPS_VERIFY_RESEND_LIMIT: overrides?.SIGNUPS_VERIFY_RESEND_LIMIT ?? 6,
    SIGNUPS_DOMAINS_WHITELIST: overrides?.SIGNUPS_DOMAINS_WHITELIST ?? "",
    INVITATIONS_ALLOWED: overrides?.INVITATIONS_ALLOWED ?? true,
    INVITATION_EXPIRATION_HOURS: overrides?.INVITATION_EXPIRATION_HOURS ?? 120,
    EMERGENCY_ACCESS_ALLOWED: overrides?.EMERGENCY_ACCESS_ALLOWED ?? true,
    PASSWORD_ITERATIONS: overrides?.PASSWORD_ITERATIONS ?? 600_000,
    PASSWORD_HINTS_ALLOWED: overrides?.PASSWORD_HINTS_ALLOWED ?? true,
    MAIL_ENABLED: overrides?.MAIL_ENABLED ?? false,
    UNAUTHENTICATED_RATELIMIT_SECONDS: overrides?.UNAUTHENTICATED_RATELIMIT_SECONDS ?? 60,
    UNAUTHENTICATED_RATELIMIT_MAX_BURST: overrides?.UNAUTHENTICATED_RATELIMIT_MAX_BURST ?? 50,
  }
}
