export const bitwardenApiRoutes = {
  prelogin: {
    method: "POST",
    paths: ["/api/accounts/prelogin", "/identity/accounts/prelogin", "/identity/accounts/prelogin/password"],
  },
  token: { method: "POST", path: "/identity/connect/token" },
  revisionDate: { method: "GET", path: "/api/accounts/revision-date" },
  sync: { method: "GET", path: "/api/sync" },
  cipherList: { method: "GET", path: "/api/ciphers" },
  cipherRead: { method: "GET", path: "/api/ciphers/:cipher_id" },
  cipherCreate: { method: "POST", path: "/api/ciphers" },
  cipherCreateWrapped: { method: "POST", path: "/api/ciphers/create" },
  cipherUpdate: { method: "PUT", path: "/api/ciphers/:cipher_id" },
  cipherPartial: { method: "PUT", path: "/api/ciphers/:cipher_id/partial" },
  cipherDelete: { method: "PUT", path: "/api/ciphers/:cipher_id/delete" },
  cipherHardDelete: { method: "DELETE", path: "/api/ciphers/:cipher_id" },
  cipherRestore: { method: "PUT", path: "/api/ciphers/:cipher_id/restore" },
  cipherArchive: { method: "PUT", path: "/api/ciphers/:cipher_id/archive" },
  cipherUnarchive: { method: "PUT", path: "/api/ciphers/:cipher_id/unarchive" },
  cipherMove: { method: "POST", path: "/api/ciphers/move" },
  cipherCollections: { method: "PUT", path: "/api/ciphers/:cipher_id/collections_v2" },
  attachmentUpload: { method: "POST", path: "/api/ciphers/:cipher_id/attachment" },
  attachmentDownload: {
    method: "GET",
    path: "/api/ciphers/:cipher_id/attachment/:attachment_id/data",
  },
  attachmentDelete: {
    method: "DELETE",
    path: "/api/ciphers/:cipher_id/attachment/:attachment_id",
  },
  folderList: { method: "GET", path: "/api/folders" },
  folderRead: { method: "GET", path: "/api/folders/:folder_id" },
  folderCreate: { method: "POST", path: "/api/folders" },
  folderUpdate: { method: "PUT", path: "/api/folders/:folder_id" },
  folderDelete: { method: "DELETE", path: "/api/folders/:folder_id" },
  collectionList: { method: "GET", path: "/api/collections" },
  collectionRead: { method: "GET", path: "/api/organizations/:org_id/collections/:col_id/details" },
  collectionCreate: { method: "POST", path: "/api/organizations/:org_id/collections" },
  collectionUpdate: { method: "PUT", path: "/api/organizations/:org_id/collections/:col_id" },
  collectionDelete: { method: "DELETE", path: "/api/organizations/:org_id/collections/:col_id" },
} as const
